/* ==========================================================================
   Crop Circle Watch — research-app.js
   Renders research.html from `window.RESEARCH` (generated by
   analytics/export_research_json.py).

   Deliberately separate from app.js: that file is ~45 KB and already owns the
   timeline, rail, search, filters and hero widgets. This page shares only the
   stylesheet and the header/footer shell.

   Charts are hand-rolled inline SVG — no chart library, keeping the site's
   zero-third-party-JS property. Every mark colour comes from a CSS custom
   property (--cat-*, --seq-*, --div-*) so the charts re-theme with the site
   instead of hardcoding hexes. Those values were machine-validated for
   colour-vision-deficiency separation and contrast against the panel surface;
   see the comment block in styles.css before changing any of them.

   Chart conventions followed throughout:
     · one measure per axis — never a second y-scale
     · categorical hues assigned in fixed order, never cycled; the tail of a
       long-tailed distribution folds into one "Other" bucket
     · a legend whenever 2+ series share a plot; single-series plots are named
       by the card title instead
     · values labelled selectively, not on every mark
     · grid and axes recessive; marks carry the eye
     · every chart also offers a table view, and honours prefers-reduced-motion
   ========================================================================== */

(function () {
  'use strict';

  var R = window.RESEARCH || null;
  var meta = window.DASHBOARD_META || {};

  var SVG_NS = 'http://www.w3.org/2000/svg';

  // Fixed internal coordinate system; the SVG scales to its container via
  // viewBox, so these are layout units rather than pixels.
  var W = 760;

  // ---------------------------------------------------------------- helpers

  function el(tag, attrs, text) {
    var n = document.createElementNS(SVG_NS, tag);
    if (attrs) Object.keys(attrs).forEach(function (k) { n.setAttribute(k, attrs[k]); });
    if (text != null) n.textContent = text;
    return n;
  }

  function h(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  function catVar(i) { return 'var(--cat-' + ((i % 8) + 1) + ')'; }

  function fmt(n, digits) {
    if (n == null || isNaN(n)) return '—';
    var d = digits == null ? 0 : digits;
    return Number(n).toLocaleString(undefined, {
      minimumFractionDigits: d, maximumFractionDigits: d
    });
  }

  function pct(n) { return n == null ? '—' : fmt(n, 1) + '%'; }

  // "Nice" axis maximum, so gridlines land on round numbers. The step ladder is
  // deliberately fine-grained — a coarse one (1/2/5/10) pushes a max of 114 up
  // to 200 and leaves half the plot empty.
  var NICE_STEPS = [1, 1.2, 1.5, 2, 2.5, 3, 4, 5, 6, 8, 10];
  function niceMax(v) {
    if (v <= 0) return 1;
    var mag = Math.pow(10, Math.floor(Math.log10(v)));
    var norm = v / mag;
    for (var i = 0; i < NICE_STEPS.length; i++) {
      if (norm <= NICE_STEPS[i]) return NICE_STEPS[i] * mag;
    }
    return 10 * mag;
  }

  // Gridline values. Prefers a divisor that yields whole-number labels, so a
  // max of 250 ticks as 0/50/…/250 rather than 0/62.5/…
  function ticks(max, preferred) {
    var candidates = [preferred, 5, 4, 3, 2];
    var count = candidates.filter(function (c) {
      return c && Number.isInteger(max / c);
    })[0] || preferred;
    var out = [];
    for (var i = 0; i <= count; i++) out.push(max * i / count);
    return out;
  }

  // ---------------------------------------------------------------- tooltip

  var tip = h('div', 'r-tip');
  tip.setAttribute('role', 'status');
  document.body.appendChild(tip);

  function showTip(evt, label, value) {
    tip.innerHTML = '';
    var l = h('span', 'r-tip-label', label + '  ');
    tip.appendChild(l);
    tip.appendChild(document.createTextNode(value));
    tip.classList.add('is-on');
    moveTip(evt);
  }

  function moveTip(evt) {
    var pad = 14;
    var x = evt.clientX + pad;
    var y = evt.clientY + pad;
    var r = tip.getBoundingClientRect();
    if (x + r.width > window.innerWidth - 8) x = evt.clientX - r.width - pad;
    if (y + r.height > window.innerHeight - 8) y = evt.clientY - r.height - pad;
    tip.style.left = x + 'px';
    tip.style.top = y + 'px';
  }

  function hideTip() { tip.classList.remove('is-on'); }

  // Attach hover behaviour to a mark. Hit area is the mark itself plus an
  // optional larger invisible target passed as `hit`.
  function hoverable(node, label, value, hit) {
    var target = hit || node;
    target.addEventListener('mouseenter', function (e) { showTip(e, label, value); });
    target.addEventListener('mousemove', moveTip);
    target.addEventListener('mouseleave', hideTip);
  }

  // ------------------------------------------------------- chart: h-bars
  // Magnitude across named categories. One measure, so one colour by default;
  // pass opts.colorByIndex for a categorical read (used where each row is a
  // distinct entity rather than a slice of one whole).

  function barsH(data, opts) {
    opts = opts || {};
    var rowH = 30, gap = 8, padL = opts.labelWidth || 150, padR = 56, padT = 8;
    var Hgt = padT + data.length * (rowH + gap);
    var max = niceMax(Math.max.apply(null, data.map(function (d) { return d.value; })));
    var plotW = W - padL - padR;

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Bar chart'
    });

    // gridlines
    var grid = el('g', { 'class': 'r-grid' });
    ticks(max, 4).forEach(function (t) {
      var x = padL + (t / max) * plotW;
      grid.appendChild(el('line', { x1: x, y1: padT, x2: x, y2: Hgt - 4 }));
    });
    svg.appendChild(grid);

    data.forEach(function (d, i) {
      var y = padT + i * (rowH + gap);
      var w = Math.max(2, (d.value / max) * plotW);
      var fill = opts.colorByIndex ? catVar(i) : (opts.fill || 'var(--seq-3)');

      // category label
      var lbl = el('text', {
        x: padL - 10, y: y + rowH / 2 + 4, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, d.label);
      svg.appendChild(lbl);

      // 4px rounded data-end; the rect's left edge sits on the axis so the
      // rounding reads only at the value end at these sizes.
      var bar = el('rect', {
        x: padL, y: y, width: w, height: rowH, rx: 4,
        fill: fill, 'class': 'r-bar r-barh--grow'
      });
      bar.style.transitionDelay = (i * 55) + 'ms';
      svg.appendChild(bar);

      // value label, direct — this is a short list, so every row is labelled
      var vl = el('text', {
        x: padL + w + 9, y: y + rowH / 2 + 4, 'class': 'r-value-label'
      }, opts.valueFormat ? opts.valueFormat(d.value) : fmt(d.value));
      svg.appendChild(vl);

      hoverable(bar, d.label, (opts.valueFormat ? opts.valueFormat(d.value) : fmt(d.value)) +
        (opts.unit ? ' ' + opts.unit : ''));
    });

    return svg;
  }

  // ------------------------------------------------------- chart: v-bars
  // Ordered/ordinal categories (months, complexity scores). Optionally
  // highlights a subset via opts.emphasis(d) -> bool.

  function barsV(data, opts) {
    opts = opts || {};
    var Hgt = 300, padL = 44, padR = 12, padT = 16, padB = 34;
    var plotW = W - padL - padR, plotH = Hgt - padT - padB;
    var max = niceMax(Math.max.apply(null, data.map(function (d) { return d.value; })));
    var slot = plotW / data.length;
    var bw = Math.max(4, Math.min(46, slot - 8));

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Bar chart'
    });

    var grid = el('g', { 'class': 'r-grid' });
    ticks(max, 4).forEach(function (t) {
      var y = padT + plotH - (t / max) * plotH;
      grid.appendChild(el('line', { x1: padL, y1: y, x2: W - padR, y2: y }));
      svg.appendChild(el('text', {
        x: padL - 9, y: y + 3.5, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, fmt(t)));
    });
    svg.insertBefore(grid, svg.firstChild);

    data.forEach(function (d, i) {
      var bh = (d.value / max) * plotH;
      var x = padL + i * slot + (slot - bw) / 2;
      var y = padT + plotH - bh;
      var emph = opts.emphasis ? opts.emphasis(d) : false;
      var fill = emph ? (opts.emphasisFill || 'var(--seq-4)') : (opts.fill || 'var(--seq-2)');

      if (d.value > 0) {
        var bar = el('rect', {
          x: x, y: y, width: bw, height: Math.max(2, bh), rx: 4,
          fill: fill, 'class': 'r-bar r-bar--grow'
        });
        bar.style.transformOrigin = '0px ' + (padT + plotH) + 'px';
        bar.style.transitionDelay = (i * 30) + 'ms';
        svg.appendChild(bar);
        hoverable(bar, d.label, fmt(d.value) + (opts.unit ? ' ' + opts.unit : ''));
      }

      // Label every slot when there's room, else every other one.
      if (slot > 26 || i % 2 === 0) {
        svg.appendChild(el('text', {
          x: padL + i * slot + slot / 2, y: Hgt - 12,
          'text-anchor': 'middle', 'class': 'r-axis-label'
        }, d.label));
      }
    });

    var axis = el('g', { 'class': 'r-axis' });
    axis.appendChild(el('line', { x1: padL, y1: padT + plotH, x2: W - padR, y2: padT + plotH }));
    svg.appendChild(axis);

    return svg;
  }

  // ------------------------------------------------------- chart: line
  // Change over time, single series. Area fill under the line for weight;
  // the path draws itself in on scroll-reveal.

  function lineChart(data, opts) {
    opts = opts || {};
    var Hgt = 300, padL = 46, padR = 16, padT = 18, padB = 34;
    var plotW = W - padL - padR, plotH = Hgt - padT - padB;
    var max = niceMax(Math.max.apply(null, data.map(function (d) { return d.value; })));
    var n = data.length;
    var xAt = function (i) { return n === 1 ? padL + plotW / 2 : padL + (i / (n - 1)) * plotW; };
    var yAt = function (v) { return padT + plotH - (v / max) * plotH; };

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Line chart'
    });

    var grid = el('g', { 'class': 'r-grid' });
    ticks(max, 4).forEach(function (t) {
      var y = yAt(t);
      grid.appendChild(el('line', { x1: padL, y1: y, x2: W - padR, y2: y }));
      svg.appendChild(el('text', {
        x: padL - 9, y: y + 3.5, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, fmt(t)));
    });
    svg.insertBefore(grid, svg.firstChild);

    var dLine = data.map(function (d, i) {
      return (i ? 'L' : 'M') + xAt(i).toFixed(1) + ' ' + yAt(d.value).toFixed(1);
    }).join(' ');

    // area under the curve
    var gradId = 'rgrad-' + Math.random().toString(36).slice(2, 8);
    var defs = el('defs');
    var lg = el('linearGradient', { id: gradId, x1: '0', y1: '0', x2: '0', y2: '1' });
    lg.appendChild(el('stop', { offset: '0%', 'stop-color': opts.stroke || 'var(--seq-4)', 'stop-opacity': '0.28' }));
    lg.appendChild(el('stop', { offset: '100%', 'stop-color': opts.stroke || 'var(--seq-4)', 'stop-opacity': '0' }));
    defs.appendChild(lg);
    svg.appendChild(defs);

    svg.appendChild(el('path', {
      d: dLine + ' L' + xAt(n - 1).toFixed(1) + ' ' + (padT + plotH) + ' L' + xAt(0).toFixed(1) + ' ' + (padT + plotH) + ' Z',
      fill: 'url(#' + gradId + ')', 'class': 'r-area'
    }));

    var path = el('path', {
      d: dLine, stroke: opts.stroke || 'var(--seq-4)', 'class': 'r-line r-line--draw'
    });
    svg.appendChild(path);
    // Length is needed for the draw-on transition; measured after insertion.
    requestAnimationFrame(function () {
      try {
        var len = path.getTotalLength();
        path.style.setProperty('--len', len);
      } catch (e) { path.classList.remove('r-line--draw'); }
    });

    // Markers + hit targets. Only label the endpoints, never every point.
    data.forEach(function (d, i) {
      var cx = xAt(i), cy = yAt(d.value);
      var showDot = n <= 24 || i === 0 || i === n - 1;
      if (showDot) {
        svg.appendChild(el('circle', {
          cx: cx, cy: cy, r: 4.5, fill: opts.stroke || 'var(--seq-4)', 'class': 'r-dot'
        }));
      }
      var hit = el('rect', {
        x: cx - Math.max(10, plotW / n / 2), y: padT,
        width: Math.max(20, plotW / n), height: plotH, fill: 'transparent'
      });
      svg.appendChild(hit);
      hoverable(null, String(d.label), fmt(d.value) + (opts.unit ? ' ' + opts.unit : ''), hit);
    });

    // x labels — thinned so they never collide
    var every = Math.max(1, Math.ceil(n / 12));
    data.forEach(function (d, i) {
      if (i % every && i !== n - 1) return;
      svg.appendChild(el('text', {
        x: xAt(i), y: Hgt - 12, 'text-anchor': 'middle', 'class': 'r-axis-label'
      }, String(d.label)));
    });

    var axis = el('g', { 'class': 'r-axis' });
    axis.appendChild(el('line', { x1: padL, y1: padT + plotH, x2: W - padR, y2: padT + plotH }));
    svg.appendChild(axis);

    return svg;
  }

  // ------------------------------------------------------- chart: scatter
  // Geographic point cloud in plain equirectangular projection, coloured by a
  // magnitude (complexity) using the sequential ramp — one hue, light→dark.

  function scatterGeo(points, opts) {
    opts = opts || {};
    var Hgt = 420, pad = 26;
    var lats = points.map(function (p) { return p.lat; });
    var lons = points.map(function (p) { return p.lon; });
    var minLat = Math.min.apply(null, lats), maxLat = Math.max.apply(null, lats);
    var minLon = Math.min.apply(null, lons), maxLon = Math.max.apply(null, lons);
    var spanLat = (maxLat - minLat) || 1, spanLon = (maxLon - minLon) || 1;

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Geographic scatter plot'
    });

    // Graticule with degree labels. Without them this reads as an abstract
    // point cloud — the labels are what make it a projection you can orient in.
    var padB = 30, padLeft = 46;
    var plotW = W - padLeft - pad, plotH = Hgt - pad - padB;
    var deg = function (v, axis) {
      var hemi = axis === 'lat' ? (v >= 0 ? 'N' : 'S') : (v >= 0 ? 'E' : 'W');
      return Math.abs(v).toFixed(0) + '°' + hemi;
    };

    var grid = el('g', { 'class': 'r-grid' });
    for (var i = 0; i <= 4; i++) {
      var f = i / 4;
      var gy = pad + f * plotH;
      var gx = padLeft + f * plotW;
      grid.appendChild(el('line', { x1: padLeft, y1: gy, x2: W - pad, y2: gy }));
      grid.appendChild(el('line', { x1: gx, y1: pad, x2: gx, y2: pad + plotH }));
      svg.appendChild(el('text', {
        x: padLeft - 9, y: gy + 3.5, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, deg(maxLat - f * spanLat, 'lat')));
      svg.appendChild(el('text', {
        x: gx, y: Hgt - 10, 'text-anchor': 'middle', 'class': 'r-axis-label'
      }, deg(minLon + f * spanLon, 'lon')));
    }
    svg.insertBefore(grid, svg.firstChild);

    var seq = ['var(--seq-1)', 'var(--seq-2)', 'var(--seq-3)', 'var(--seq-4)', 'var(--seq-5)'];
    points.forEach(function (p) {
      var x = padLeft + ((p.lon - minLon) / spanLon) * plotW;
      var y = pad + (1 - (p.lat - minLat) / spanLat) * plotH;
      var band = Math.min(4, Math.max(0, Math.round(((p.c || 1) - 1) / 9 * 4)));
      // Half-transparent fill so the dense southern-England cluster reads as
      // density rather than one flat blob; the surface-coloured ring keeps
      // individual points separable where they overlap.
      var dot = el('circle', {
        cx: x.toFixed(1), cy: y.toFixed(1), r: 4,
        fill: seq[band], 'fill-opacity': '0.7',
        stroke: 'var(--chart-surface)', 'stroke-width': '0.75'
      });
      svg.appendChild(dot);
      hoverable(dot, p.name, 'complexity ' + p.c + ' · ' + p.lat.toFixed(2) + ', ' + p.lon.toFixed(2));
    });

    return svg;
  }

  // ------------------------------------ chart: hypothesis confidence bars
  // Ordinal 0-5 confidence per hypothesis. Categorical hues in fixed order
  // (each hypothesis is a distinct entity), and the level is ALSO printed as
  // text so identity never rests on colour alone.

  function confidenceBars(items, scaleMax) {
    // padL has to clear the longest "H3 · Electromagnetic / plasma vortex"
    // label — text-anchor:end means an undersized gutter clips off the left
    // edge rather than wrapping.
    var rowH = 34, gap = 10, padL = 252, padR = 104, padT = 6;
    var Hgt = padT + items.length * (rowH + gap);
    var plotW = W - padL - padR;

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': 'Confidence level by hypothesis'
    });

    // step ticks
    var grid = el('g', { 'class': 'r-grid' });
    for (var s = 0; s <= scaleMax; s++) {
      var x = padL + (s / scaleMax) * plotW;
      grid.appendChild(el('line', { x1: x, y1: padT, x2: x, y2: Hgt - 6 }));
    }
    svg.appendChild(grid);

    items.forEach(function (it, i) {
      var y = padT + i * (rowH + gap);
      var w = Math.max(3, ((it.score || 0) / scaleMax) * plotW);

      svg.appendChild(el('text', {
        x: padL - 12, y: y + rowH / 2 + 4, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, it.id + ' · ' + it.name));

      var bar = el('rect', {
        x: padL, y: y, width: w, height: rowH, rx: 4,
        fill: catVar(i), 'class': 'r-bar r-barh--grow'
      });
      bar.style.transitionDelay = (i * 60) + 'ms';
      svg.appendChild(bar);

      svg.appendChild(el('text', {
        x: padL + w + 10, y: y + rowH / 2 + 4, 'class': 'r-value-label'
      }, it.label || '—'));

      hoverable(bar, it.id + ' ' + it.name, (it.label || '—') + ' (' + (it.score == null ? '—' : it.score) + '/' + scaleMax + ')');
    });

    return svg;
  }

  // -------------------------------------------------------------- building

  function legend(entries) {
    var wrap = h('div', 'r-legend');
    entries.forEach(function (e) {
      var item = h('span', 'r-legend-item');
      var sw = h('span', 'r-legend-swatch');
      sw.style.background = e.color;
      item.appendChild(sw);
      item.appendChild(document.createTextNode(e.label));
      wrap.appendChild(item);
    });
    return wrap;
  }

  // Every chart ships a table view — the accessible fallback and the answer to
  // "what exactly is that bar".
  function tableView(cols, rows) {
    var wrap = h('div', 'r-table-wrap');
    wrap.hidden = true;
    var t = h('table', 'r-table');
    var thead = document.createElement('thead');
    var tr = document.createElement('tr');
    cols.forEach(function (c) { tr.appendChild(h('th', null, c)); });
    thead.appendChild(tr);
    t.appendChild(thead);
    var tb = document.createElement('tbody');
    rows.forEach(function (r) {
      var row = document.createElement('tr');
      r.forEach(function (cell) { row.appendChild(h('td', null, String(cell))); });
      tb.appendChild(row);
    });
    t.appendChild(tb);
    wrap.appendChild(t);

    var btn = h('button', 'r-table-toggle', 'Show data table');
    btn.type = 'button';
    btn.setAttribute('aria-expanded', 'false');
    btn.addEventListener('click', function () {
      var open = !wrap.hidden;
      wrap.hidden = open;
      btn.setAttribute('aria-expanded', String(!open));
      btn.textContent = open ? 'Show data table' : 'Hide data table';
    });

    var frag = document.createDocumentFragment();
    frag.appendChild(btn);
    frag.appendChild(wrap);
    return frag;
  }

  function deltaChip(value, unit, opts) {
    opts = opts || {};
    if (value == null || isNaN(value)) return null;
    var dir = value > 0 ? 'up' : value < 0 ? 'down' : 'flat';
    // Direction is spelled out; the colour is reinforcement, not the signal.
    var arrow = dir === 'up' ? '▲' : dir === 'down' ? '▼' : '■';
    var word = dir === 'flat' ? 'no change' :
      (dir === 'up' ? '+' : '') + fmt(value, opts.digits == null ? 1 : opts.digits) + (unit || '');
    var chip = h('span', 'r-delta r-delta--' + dir);
    chip.appendChild(document.createTextNode(arrow + ' ' + word + ' vs last week'));
    return chip;
  }

  function card(opts) {
    var c = h('article', 'r-card');
    var head = h('div', 'r-card-head');
    if (opts.kicker) head.appendChild(h('p', 'r-kicker', opts.kicker));
    head.appendChild(h('h2', 'r-title', opts.title));
    c.appendChild(head);

    if (opts.hero) {
      var fig = h('div', 'r-hero-figure');
      fig.appendChild(h('span', 'r-hero-value', opts.hero.value));
      if (opts.hero.unit) fig.appendChild(h('span', 'r-hero-unit', opts.hero.unit));
      if (opts.hero.delta) fig.appendChild(opts.hero.delta);
      c.appendChild(fig);
    }

    if (opts.chart) {
      var scroll = h('div', 'r-chart-scroll');
      scroll.appendChild(opts.chart);
      c.appendChild(scroll);
    }
    if (opts.legend) c.appendChild(opts.legend);
    if (opts.reading) c.appendChild(h('p', 'r-reading', opts.reading));
    if (opts.table) c.appendChild(opts.table);
    return c;
  }

  function tiles(items) {
    var wrap = h('div', 'r-tiles');
    items.forEach(function (t) {
      var tile = h('div', 'r-tile');
      tile.appendChild(h('div', 'r-tile-label', t.label));
      tile.appendChild(h('div', 'r-tile-value', t.value));
      if (t.sub) tile.appendChild(h('div', 'r-tile-sub', t.sub));
      wrap.appendChild(tile);
    });
    return wrap;
  }

  // ------------------------------------------------------------------ tabs

  var TABS = [
    { id: 'geography', label: 'Geography', build: buildGeography },
    { id: 'time', label: 'Time & season', build: buildTime },
    { id: 'geometry', label: 'Geometry & pattern', build: buildGeometry },
    { id: 'hypotheses', label: 'Hypotheses', build: buildHypotheses },
    { id: 'health', label: 'Dataset health', build: buildHealth }
  ];

  function buildGeography() {
    var g = R.geography, m = R.metrics, out = [];

    out.push(card({
      kicker: 'Distribution',
      title: 'Where formations are reported',
      hero: {
        value: pct(m.ukPct),
        unit: 'of all recorded formations are in the UK',
        delta: null
      },
      chart: barsH(g.countries, {
        ariaLabel: 'Formations by country',
        labelWidth: 150,
        unit: 'formations'
      }),
      reading: 'The archive is heavily UK-weighted, and that is a fact about the ' +
        'record rather than necessarily about the phenomenon: the UK has the ' +
        'densest reporting infrastructure, the longest-running documentation ' +
        'groups, and the most active aerial photographers. Countries in the ' +
        '"Other" bucket each contribute fewer than eleven formations.',
      table: tableView(['Country', 'Formations'],
        g.countries.map(function (d) { return [d.label, d.value]; }))
    }));

    out.push(card({
      kicker: 'Concentration',
      title: 'Within the UK, one county dominates',
      hero: {
        value: pct(m.wiltshirePct),
        unit: 'of the entire archive is Wiltshire alone',
        delta: deltaChip(R.deltas.wiltshirePct, 'pp')
      },
      chart: barsH(g.ukRegions, {
        ariaLabel: 'UK formations by county',
        labelWidth: 150,
        unit: 'formations'
      }),
      reading: 'Wiltshire accounts for more formations than every non-UK country ' +
        'combined. The county sits on chalk downland with large open fields and ' +
        'a dense concentration of neolithic monuments — and it is also where ' +
        'nearly all dedicated crop circle researchers are based, so observation ' +
        'effort and formation count are hard to separate here.',
      table: tableView(['County', 'Formations'],
        g.ukRegions.map(function (d) { return [d.label, d.value]; }))
    }));

    if (g.points && g.points.length) {
      out.push(card({
        kicker: 'Spatial',
        title: 'Every geolocated formation, plotted',
        chart: scatterGeo(g.points, { ariaLabel: 'Formation locations by latitude and longitude' }),
        legend: legend([
          { label: 'complexity 1–2', color: 'var(--seq-1)' },
          { label: '3–4', color: 'var(--seq-2)' },
          { label: '5–6', color: 'var(--seq-3)' },
          { label: '7–8', color: 'var(--seq-4)' },
          { label: '9–10', color: 'var(--seq-5)' }
        ]),
        reading: 'All ' + fmt(g.points.length) + ' geolocated formations are plotted ' +
          'here by latitude and longitude, shaded by complexity score — but far ' +
          'fewer than ' + fmt(g.points.length) + ' dots are visible, because most ' +
          'of them land on top of each other. The dense knot near 2°W, 51°N is ' +
          'southern England, where roughly half the archive sits inside about two ' +
          'degrees of latitude; at world scale those hundreds of formations collapse ' +
          'into a single smudge. The scattered points are the international record. ' +
          'Hover any point for its name. The engine currently resolves ' +
          fmt(m.clusters) + ' distinct spatial clusters.'
      }));
    }

    var near = g.nearAncientSite;
    out.push(card({
      kicker: 'Proximity',
      title: 'Distance to the nearest ancient site',
      chart: null,
      hero: {
        value: pct(m.nearSitePct),
        unit: 'appear near a known ancient site',
        delta: deltaChip(R.deltas.nearSitePct, 'pp')
      },
      reading: 'Of ' + fmt(near.near + near.far) + ' formations, ' + fmt(near.near) +
        ' fall within the engine\'s "near ancient site" threshold and ' + fmt(near.far) +
        ' do not. The difference in mean distance tests as statistically significant ' +
        '(t = ' + fmt(near.tStat, 2) + ', p = ' + fmt(near.pValue, 4) + '), which is ' +
        'the strongest geographic signal in the dataset — though proximity to ' +
        'monuments and proximity to Wiltshire chalk downland are themselves ' +
        'correlated, so this is not yet an independent finding.'
    }));

    out[out.length - 1].insertBefore(
      tiles([
        { label: 'Near a site', value: fmt(near.near), sub: 'formations' },
        { label: 'Not near', value: fmt(near.far), sub: 'formations' },
        { label: 'Mean distance', value: fmt(near.meanDistKm, 2), sub: 'km to nearest site' },
        { label: 'Significance', value: 'p ' + fmt(near.pValue, 3), sub: 't = ' + fmt(near.tStat, 2) }
      ]),
      out[out.length - 1].querySelector('.r-reading')
    );

    return out;
  }

  function buildTime() {
    var t = R.time, out = [];

    out.push(card({
      kicker: 'Seasonality',
      title: 'Formations follow the harvest',
      hero: {
        value: pct(t.summerPct),
        unit: 'of all formations appear June–August',
        delta: null
      },
      chart: barsV(t.perMonth, {
        ariaLabel: 'Formations by month of year',
        unit: 'formations',
        emphasis: function (d) { return d.month >= 6 && d.month <= 8; },
        emphasisFill: 'var(--seq-4)',
        fill: 'var(--seq-2)'
      }),
      legend: legend([
        { label: 'June–August', color: 'var(--seq-4)' },
        { label: 'rest of year', color: 'var(--seq-2)' }
      ]),
      reading: 'This is the least mysterious pattern in the archive and the most ' +
        'important one to state plainly: formations appear when there is standing ' +
        'crop tall enough to lay down. The season opens as winter wheat reaches ' +
        'height and closes at harvest. Any explanation — human or otherwise — has ' +
        'to operate inside that window, so seasonality discriminates between ' +
        'hypotheses far less than it first appears to.',
      table: tableView(['Month', 'Formations'],
        t.perMonth.map(function (d) { return [d.label, d.value]; }))
    }));

    if (t.perYear && t.perYear.length) {
      out.push(card({
        kicker: 'Over time',
        title: 'Reported formations per year',
        chart: lineChart(t.perYear, {
          ariaLabel: 'Formations reported per year since 1970',
          unit: 'formations',
          stroke: 'var(--seq-4)'
        }),
        reading: 'The record rises sharply through the 1990s — the period when crop ' +
          'circles became a mass-media subject and dedicated documentation groups ' +
          'formed — then settles. Read this as a curve of documentation effort at ' +
          'least as much as one of formation frequency: the archive can only ' +
          'contain what somebody recorded. The apparent fall in the most recent ' +
          'year is normally just the current season still being incomplete.',
        table: tableView(['Year', 'Formations'],
          t.perYear.map(function (d) { return [d.label, d.value]; }))
      }));
    }

    return out;
  }

  function buildGeometry() {
    var g = R.geometry, out = [];
    var tr = g.complexityTrend || {};

    out.push(card({
      kicker: 'Complexity',
      title: 'Most formations are simple',
      hero: {
        value: fmt(g.meanComplexity, 2),
        unit: 'mean complexity score, out of 10',
        delta: deltaChip(R.deltas.meanComplexity, '', { digits: 2 })
      },
      chart: barsV(g.complexity, {
        ariaLabel: 'Distribution of complexity scores',
        unit: 'formations',
        fill: 'var(--seq-3)'
      }),
      reading: 'The distribution is strongly weighted toward the low end — the ' +
        'archive is mostly plain circles and simple rings. The elaborate ' +
        'fractal and pictogram formations that dominate public perception of the ' +
        'subject are a small minority of the actual record, which is worth ' +
        'holding onto when assessing any explanation built on the complex ones.',
      table: tableView(['Complexity score', 'Formations'],
        g.complexity.map(function (d) { return [d.label, d.value]; }))
    }));

    out.push(card({
      kicker: 'Form',
      title: 'Geometric type breakdown',
      chart: barsH(g.types, {
        ariaLabel: 'Formations by geometric type',
        labelWidth: 190,
        unit: 'formations'
      }),
      reading: 'Simple circles outnumber every other form several times over. ' +
        'The named categories below them — pictograms, fractal spirals, ' +
        'triangular constructions — are where the archive\'s more structurally ' +
        'interesting cases sit.',
      table: tableView(['Geometric type', 'Formations'],
        g.types.map(function (d) { return [d.label, d.value]; }))
    }));

    out.push(card({
      kicker: 'Encoded features',
      title: 'Mathematical structure in the record',
      chart: barsH(g.encoded, {
        ariaLabel: 'Count of formations flagged with each encoded feature',
        labelWidth: 170,
        colorByIndex: true,
        unit: 'formations'
      }),
      reading: 'Counts of formations the engine has flagged as containing each ' +
        'feature. These flags come from the source records and the engine\'s own ' +
        'scoring rather than from independent re-measurement, so treat them as ' +
        'a research index — a list of where to look — rather than as verified ' +
        'mathematical claims about each formation.',
      table: tableView(['Feature', 'Formations'],
        g.encoded.map(function (d) { return [d.label, d.value]; }))
    }));

    out.push(card({
      kicker: 'Trend',
      title: 'Are formations getting more complex over time?',
      reading: 'Not detectably. Fitting complexity against year gives a slope of ' +
        fmt(tr.slopePerYear, 4) + ' points per year with R² = ' + fmt(tr.r2, 3) +
        ' and p = ' + fmt(tr.pValue, 3) + '. An R² that low means year explains ' +
        'essentially none of the variation in complexity, and the p-value gives ' +
        'no grounds to reject chance. The popular narrative that formations have ' +
        'grown steadily more elaborate is not supported by this dataset.'
    }));

    out[out.length - 1].insertBefore(
      tiles([
        { label: 'Slope', value: fmt(tr.slopePerYear, 4), sub: 'complexity / year' },
        { label: 'R²', value: fmt(tr.r2, 3), sub: 'variance explained' },
        { label: 'p-value', value: fmt(tr.pValue, 3), sub: tr.pValue > 0.05 ? 'not significant' : 'significant' },
        { label: 'Mean diameter', value: fmt(g.meanDiameterM, 1), sub: 'metres' }
      ]),
      out[out.length - 1].querySelector('.r-reading')
    );

    return out;
  }

  function buildHypotheses() {
    var hy = R.hypotheses, out = [];
    var leading = hy.current.reduce(function (a, b) {
      return (b.score || 0) > (a.score || 0) ? b : a;
    }, hy.current[0] || {});

    out.push(card({
      kicker: 'Current standing',
      title: 'Confidence by hypothesis',
      chart: confidenceBars(hy.current, hy.scaleMax),
      reading: 'These are the analytics engine\'s confidence ratings for each ' +
        'candidate explanation, scored from the evidence currently in the ' +
        'archive. The leading position — ' + (leading.name || '—') + ' — is not a ' +
        'claim that the question is settled; it reflects that a record containing ' +
        'both documented human-made formations and unexplained cases is better ' +
        'described by a mixed model than by any single cause. Confidence here ' +
        'means "how well the evidence supports this", not "how likely this is to ' +
        'be true".',
      table: tableView(['Hypothesis', 'Confidence', 'Score'],
        hy.current.map(function (d) { return [d.id + ' ' + d.name, d.label || '—', (d.score == null ? '—' : d.score + '/' + hy.scaleMax)]; }))
    }));

    if (hy.history && hy.history.length > 1) {
      var hist = hy.history;
      // One line per hypothesis over the tracked weeks. Six series → legend
      // plus fixed-order categorical hues.
      var Hgt = 300, padL = 46, padR = 16, padT = 18, padB = 34;
      var plotW = W - padL - padR, plotH = Hgt - padT - padB;
      var n = hist.length;
      var svg = el('svg', {
        'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
        role: 'img', 'aria-label': 'Hypothesis confidence over time'
      });
      var grid = el('g', { 'class': 'r-grid' });
      for (var s = 0; s <= hy.scaleMax; s++) {
        var y = padT + plotH - (s / hy.scaleMax) * plotH;
        grid.appendChild(el('line', { x1: padL, y1: y, x2: W - padR, y2: y }));
        svg.appendChild(el('text', {
          x: padL - 9, y: y + 3.5, 'text-anchor': 'end', 'class': 'r-axis-label'
        }, String(s)));
      }
      svg.insertBefore(grid, svg.firstChild);

      hy.current.forEach(function (hyp, hi) {
        var d = hist.map(function (row, i) {
          var x = n === 1 ? padL + plotW / 2 : padL + (i / (n - 1)) * plotW;
          var yy = padT + plotH - ((row.scores[hi] || 0) / hy.scaleMax) * plotH;
          return (i ? 'L' : 'M') + x.toFixed(1) + ' ' + yy.toFixed(1);
        }).join(' ');
        var p = el('path', { d: d, stroke: catVar(hi), 'class': 'r-line' });
        p.setAttribute('stroke-opacity', '0.9');
        svg.appendChild(p);
        var lastX = padL + plotW, lastY = padT + plotH - ((hist[n - 1].scores[hi] || 0) / hy.scaleMax) * plotH;
        var dot = el('circle', { cx: lastX, cy: lastY, r: 4.5, fill: catVar(hi), 'class': 'r-dot' });
        svg.appendChild(dot);
        hoverable(dot, hyp.id + ' ' + hyp.name, 'now ' + (hyp.label || '—'));
      });

      hist.forEach(function (row, i) {
        if (i % Math.max(1, Math.ceil(n / 8)) && i !== n - 1) return;
        svg.appendChild(el('text', {
          x: n === 1 ? padL + plotW / 2 : padL + (i / (n - 1)) * plotW,
          y: Hgt - 12, 'text-anchor': 'middle', 'class': 'r-axis-label'
        }, row.week.replace('2026-', '')));
      });
      var axis = el('g', { 'class': 'r-axis' });
      axis.appendChild(el('line', { x1: padL, y1: padT + plotH, x2: W - padR, y2: padT + plotH }));
      svg.appendChild(axis);

      out.push(card({
        kicker: 'Over time',
        title: 'How confidence has shifted',
        chart: svg,
        legend: legend(hy.current.map(function (hyp, i) {
          return { label: hyp.id + ' ' + hyp.name, color: catVar(i) };
        })),
        reading: 'Each line tracks one hypothesis across the weekly analysis runs. ' +
          'The large step change corresponds to the dataset roughly quadrupling ' +
          'in size — when the archive grew from the seed set to the full research ' +
          'record, several ratings moved at once. Stability since then reflects a ' +
          'settled dataset, not a settled question.',
        table: tableView(['Week'].concat(hy.current.map(function (x) { return x.id; })),
          hist.map(function (r) { return [r.week].concat(r.scores); }))
      }));
    }

    return out;
  }

  function buildHealth() {
    var hl = R.health, out = [];

    if (hl.growth && hl.growth.length) {
      out.push(card({
        kicker: 'Coverage',
        title: 'Archive growth, week by week',
        hero: {
          value: fmt(R.metrics.total),
          unit: 'formations in the dataset',
          delta: deltaChip(R.deltas.total, '', { digits: 0 })
        },
        chart: lineChart(hl.growth.map(function (d) {
          return { label: d.week.replace('2026-', ''), value: d.value };
        }), { ariaLabel: 'Dataset size by analysis week', unit: 'formations', stroke: 'var(--seq-4)' }),
        reading: 'Dataset size at each weekly run. The step is the point where the ' +
          'seed dataset was replaced by the full research archive; growth since ' +
          'then comes from the daily research agent. A flat week means no new ' +
          'formations cleared verification — which is a normal outcome, not a ' +
          'failure of the scan.',
        table: tableView(['Week', 'Formations'],
          hl.growth.map(function (d) { return [d.week, d.value]; }))
      }));
    }

    out.push(card({
      kicker: 'Data quality',
      title: 'Field completeness',
      chart: barsH(hl.completeness, {
        ariaLabel: 'Percentage of records with each field populated',
        labelWidth: 170,
        unit: '% populated',
        valueFormat: function (v) { return fmt(v, 1) + '%'; }
      }),
      reading: 'How much of each field is actually populated across the archive. ' +
        'Coordinates and complexity are near-complete; physical measurements like ' +
        'diameter are the weakest, because most source reports simply never state ' +
        'one. Any statistic derived from a sparse field carries that gap with it — ' +
        'the mean diameter is a mean over the subset that reported a diameter, not ' +
        'over the archive.',
      table: tableView(['Field', '% populated'],
        hl.completeness.map(function (d) { return [d.label, d.value + '%']; }))
    }));

    out.push(card({
      kicker: 'Known gaps',
      title: 'What this dataset cannot tell you',
      reading: 'Three limits worth stating outright. First, ' + fmt(hl.unknownMediaCoverage) +
        ' records have unknown media coverage, so anything about publicity is ' +
        'unreliable. Second, the archive is a record of *reports*, and reporting ' +
        'effort is concentrated in one county of one country — geographic patterns ' +
        'partly measure where people are looking. Third, the confidence ratings ' +
        'are an evidence-weighting exercise by an automated pipeline, not peer ' +
        'review. The value here is in the shape of the record and in knowing ' +
        'exactly where it is thin.'
    }));

    return out;
  }

  // ----------------------------------------------------------------- render

  var elFeed = document.getElementById('researchFeed');
  var elTabs = document.getElementById('researchTabs');

  var observer = ('IntersectionObserver' in window)
    ? new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          if (e.isIntersecting) {
            e.target.classList.add('is-in');
            observer.unobserve(e.target);
          }
        });
      }, { rootMargin: '0px 0px -8% 0px', threshold: 0.06 })
    : null;

  function selectTab(id) {
    [].forEach.call(elTabs.children, function (b) {
      b.setAttribute('aria-selected', String(b.dataset.tab === id));
    });
    elFeed.innerHTML = '';
    hideTip();
    var tab = TABS.filter(function (t) { return t.id === id; })[0];
    if (!tab) return;
    tab.build().forEach(function (c) {
      elFeed.appendChild(c);
      if (observer) observer.observe(c);
      else c.classList.add('is-in');
    });
    try {
      history.replaceState(null, '', '#' + id);
    } catch (e) { /* file:// — harmless */ }
  }

  function renderStamp() {
    var span = R.time && R.time.yearRange;
    var set = function (id, v) {
      var n = document.getElementById(id);
      if (n) n.textContent = v;
    };
    set('rsTotal', fmt(R.metrics.total) + ' formations');
    set('rsWeek', R.week || '—');
    set('rsSpan', span ? span[0] + '–' + span[1] : '—');

    // Same scan stamp the other two pages show, in the header chip and footer.
    if (meta.lastScan) {
      var stamp;
      try {
        stamp = new Intl.DateTimeFormat(undefined, {
          month: 'short', day: 'numeric', hour: 'numeric',
          minute: '2-digit', timeZoneName: 'short'
        }).format(new Date(meta.lastScan)).toUpperCase();
      } catch (e) { stamp = meta.lastScan; }
      ['statScan', 'footerUpdated'].forEach(function (id) {
        var n = document.getElementById(id);
        if (n) n.textContent = stamp;
      });
    }
  }

  function init() {
    if (!R) {
      elFeed.innerHTML =
        '<p class="r-reading">Research data hasn\'t been generated yet. Run ' +
        '<code>python3 analytics/export_research_json.py</code> to build ' +
        '<code>research.js</code>.</p>';
      return;
    }

    TABS.forEach(function (t, i) {
      var b = h('button', 'research-tab', t.label);
      b.type = 'button';
      b.dataset.tab = t.id;
      b.setAttribute('role', 'tab');
      b.setAttribute('aria-selected', String(i === 0));
      b.addEventListener('click', function () { selectTab(t.id); });
      elTabs.appendChild(b);
    });

    renderStamp();

    var fromHash = (location.hash || '').replace('#', '');
    var initial = TABS.some(function (t) { return t.id === fromHash; }) ? fromHash : TABS[0].id;
    selectTab(initial);
  }

  init();
})();
