/* ==========================================================================
   Crop Circle Watch — research-app.js
   Renders research.html from `window.RESEARCH` (generated by
   analytics/export_research_json.py).

   Deliberately separate from app.js: that file is ~45 KB and already owns the
   timeline, rail, search, filters and hero widgets. This page shares only the
   stylesheet and the header/footer shell.

   Charts are hand-rolled inline SVG — no chart library, keeping the site's
   zero-third-party-JS property. Every mark colour comes from a CSS custom
   property (--cat-*, --seq-*, --div-*) so the charts re-theme with the site
   instead of hardcoding hexes. Those values were machine-validated for
   colour-vision-deficiency separation and contrast against the panel surface;
   see the comment block in styles.css before changing any of them.

   Chart conventions followed throughout:
     · one measure per axis — never a second y-scale
     · categorical hues assigned in fixed order, never cycled; the tail of a
       long-tailed distribution folds into one "Other" bucket
     · a legend whenever 2+ series share a plot; single-series plots are named
       by the card title instead
     · values labelled selectively, not on every mark
     · grid and axes recessive; marks carry the eye
     · every chart also offers a table view, and honours prefers-reduced-motion
   ========================================================================== */

(function () {
  'use strict';

  var R = window.RESEARCH || null;
  var meta = window.DASHBOARD_META || {};

  var SVG_NS = 'http://www.w3.org/2000/svg';

  // Fixed internal coordinate system; the SVG scales to its container via
  // viewBox, so these are layout units rather than pixels.
  var W = 760;

  // ---------------------------------------------------------------- helpers

  function el(tag, attrs, text) {
    var n = document.createElementNS(SVG_NS, tag);
    if (attrs) Object.keys(attrs).forEach(function (k) { n.setAttribute(k, attrs[k]); });
    if (text != null) n.textContent = text;
    return n;
  }

  function h(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  function catVar(i) { return 'var(--cat-' + ((i % 8) + 1) + ')'; }

  function fmt(n, digits) {
    if (n == null || isNaN(n)) return '—';
    var d = digits == null ? 0 : digits;
    return Number(n).toLocaleString(undefined, {
      minimumFractionDigits: d, maximumFractionDigits: d
    });
  }

  function pct(n) { return n == null ? '—' : fmt(n, 1) + '%'; }

  // "Nice" axis maximum, so gridlines land on round numbers. The step ladder is
  // deliberately fine-grained — a coarse one (1/2/5/10) pushes a max of 114 up
  // to 200 and leaves half the plot empty.
  var NICE_STEPS = [1, 1.2, 1.5, 2, 2.5, 3, 4, 5, 6, 8, 10];
  function niceMax(v) {
    if (v <= 0) return 1;
    var mag = Math.pow(10, Math.floor(Math.log10(v)));
    var norm = v / mag;
    for (var i = 0; i < NICE_STEPS.length; i++) {
      if (norm <= NICE_STEPS[i]) return NICE_STEPS[i] * mag;
    }
    return 10 * mag;
  }

  // Gridline values. Prefers a divisor that yields whole-number labels, so a
  // max of 250 ticks as 0/50/…/250 rather than 0/62.5/…
  function ticks(max, preferred) {
    var candidates = [preferred, 5, 4, 3, 2];
    var count = candidates.filter(function (c) {
      return c && Number.isInteger(max / c);
    })[0] || preferred;
    var out = [];
    for (var i = 0; i <= count; i++) out.push(max * i / count);
    return out;
  }

  // ---------------------------------------------------------------- tooltip

  var tip = h('div', 'r-tip');
  tip.setAttribute('role', 'status');
  document.body.appendChild(tip);

  function showTip(evt, label, value) {
    tip.innerHTML = '';
    var l = h('span', 'r-tip-label', label + '  ');
    tip.appendChild(l);
    tip.appendChild(document.createTextNode(value));
    tip.classList.add('is-on');
    moveTip(evt);
  }

  function moveTip(evt) {
    var pad = 14;
    var x = evt.clientX + pad;
    var y = evt.clientY + pad;
    var r = tip.getBoundingClientRect();
    if (x + r.width > window.innerWidth - 8) x = evt.clientX - r.width - pad;
    if (y + r.height > window.innerHeight - 8) y = evt.clientY - r.height - pad;
    tip.style.left = x + 'px';
    tip.style.top = y + 'px';
  }

  function hideTip() { tip.classList.remove('is-on'); }

  // Attach hover behaviour to a mark. Hit area is the mark itself plus an
  // optional larger invisible target passed as `hit`.
  function hoverable(node, label, value, hit) {
    var target = hit || node;
    target.addEventListener('mouseenter', function (e) { showTip(e, label, value); });
    target.addEventListener('mousemove', moveTip);
    target.addEventListener('mouseleave', hideTip);
  }

  // ------------------------------------------------------- chart: h-bars
  // Magnitude across named categories. One measure, so one colour by default;
  // pass opts.colorByIndex for a categorical read (used where each row is a
  // distinct entity rather than a slice of one whole).

  function barsH(data, opts) {
    opts = opts || {};
    var rowH = 30, gap = 8, padL = opts.labelWidth || 150, padR = 56, padT = 8;
    var Hgt = padT + data.length * (rowH + gap);
    var max = niceMax(Math.max.apply(null, data.map(function (d) { return d.value; })));
    var plotW = W - padL - padR;

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Bar chart'
    });

    // gridlines
    var grid = el('g', { 'class': 'r-grid' });
    ticks(max, 4).forEach(function (t) {
      var x = padL + (t / max) * plotW;
      grid.appendChild(el('line', { x1: x, y1: padT, x2: x, y2: Hgt - 4 }));
    });
    svg.appendChild(grid);

    data.forEach(function (d, i) {
      var y = padT + i * (rowH + gap);
      var w = Math.max(2, (d.value / max) * plotW);
      var fill = opts.colorByIndex ? catVar(i) : (opts.fill || 'var(--seq-3)');

      // category label
      var lbl = el('text', {
        x: padL - 10, y: y + rowH / 2 + 4, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, d.label);
      svg.appendChild(lbl);

      // 4px rounded data-end; the rect's left edge sits on the axis so the
      // rounding reads only at the value end at these sizes.
      var bar = el('rect', {
        x: padL, y: y, width: w, height: rowH, rx: 4,
        fill: fill, 'class': 'r-bar r-barh--grow'
      });
      bar.style.transitionDelay = (i * 55) + 'ms';
      svg.appendChild(bar);

      // value label, direct — this is a short list, so every row is labelled
      var vl = el('text', {
        x: padL + w + 9, y: y + rowH / 2 + 4, 'class': 'r-value-label'
      }, opts.valueFormat ? opts.valueFormat(d.value) : fmt(d.value));
      svg.appendChild(vl);

      hoverable(bar, d.label, (opts.valueFormat ? opts.valueFormat(d.value) : fmt(d.value)) +
        (opts.unit ? ' ' + opts.unit : ''));
    });

    return svg;
  }

  // ------------------------------------------------------- chart: v-bars
  // Ordered/ordinal categories (months, complexity scores). Optionally
  // highlights a subset via opts.emphasis(d) -> bool.

  function barsV(data, opts) {
    opts = opts || {};
    var Hgt = 300, padL = 44, padR = 12, padT = 16, padB = 34;
    var plotW = W - padL - padR, plotH = Hgt - padT - padB;
    var max = niceMax(Math.max.apply(null, data.map(function (d) { return d.value; })));
    var slot = plotW / data.length;
    var bw = Math.max(4, Math.min(46, slot - 8));

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Bar chart'
    });

    var grid = el('g', { 'class': 'r-grid' });
    ticks(max, 4).forEach(function (t) {
      var y = padT + plotH - (t / max) * plotH;
      grid.appendChild(el('line', { x1: padL, y1: y, x2: W - padR, y2: y }));
      svg.appendChild(el('text', {
        x: padL - 9, y: y + 3.5, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, fmt(t)));
    });
    svg.insertBefore(grid, svg.firstChild);

    data.forEach(function (d, i) {
      var bh = (d.value / max) * plotH;
      var x = padL + i * slot + (slot - bw) / 2;
      var y = padT + plotH - bh;
      var emph = opts.emphasis ? opts.emphasis(d) : false;
      var fill = emph ? (opts.emphasisFill || 'var(--seq-4)') : (opts.fill || 'var(--seq-2)');

      if (d.value > 0) {
        var bar = el('rect', {
          x: x, y: y, width: bw, height: Math.max(2, bh), rx: 4,
          fill: fill, 'class': 'r-bar r-bar--grow'
        });
        bar.style.transformOrigin = '0px ' + (padT + plotH) + 'px';
        bar.style.transitionDelay = (i * 30) + 'ms';
        svg.appendChild(bar);
        hoverable(bar, d.label, fmt(d.value) + (opts.unit ? ' ' + opts.unit : ''));
      }

      // Label every slot when there's room, else every other one.
      if (slot > 26 || i % 2 === 0) {
        svg.appendChild(el('text', {
          x: padL + i * slot + slot / 2, y: Hgt - 12,
          'text-anchor': 'middle', 'class': 'r-axis-label'
        }, d.label));
      }
    });

    var axis = el('g', { 'class': 'r-axis' });
    axis.appendChild(el('line', { x1: padL, y1: padT + plotH, x2: W - padR, y2: padT + plotH }));
    svg.appendChild(axis);

    return svg;
  }

  // ------------------------------------------------------- chart: line
  // Change over time, single series. Area fill under the line for weight;
  // the path draws itself in on scroll-reveal.

  function lineChart(data, opts) {
    opts = opts || {};
    var Hgt = 300, padL = 46, padR = 16, padT = 18, padB = 34;
    var plotW = W - padL - padR, plotH = Hgt - padT - padB;
    var max = niceMax(Math.max.apply(null, data.map(function (d) { return d.value; })));
    var n = data.length;
    var xAt = function (i) { return n === 1 ? padL + plotW / 2 : padL + (i / (n - 1)) * plotW; };
    var yAt = function (v) { return padT + plotH - (v / max) * plotH; };

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Line chart'
    });

    var grid = el('g', { 'class': 'r-grid' });
    ticks(max, 4).forEach(function (t) {
      var y = yAt(t);
      grid.appendChild(el('line', { x1: padL, y1: y, x2: W - padR, y2: y }));
      svg.appendChild(el('text', {
        x: padL - 9, y: y + 3.5, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, fmt(t)));
    });
    svg.insertBefore(grid, svg.firstChild);

    var dLine = data.map(function (d, i) {
      return (i ? 'L' : 'M') + xAt(i).toFixed(1) + ' ' + yAt(d.value).toFixed(1);
    }).join(' ');

    // area under the curve
    var gradId = 'rgrad-' + Math.random().toString(36).slice(2, 8);
    var defs = el('defs');
    var lg = el('linearGradient', { id: gradId, x1: '0', y1: '0', x2: '0', y2: '1' });
    lg.appendChild(el('stop', { offset: '0%', 'stop-color': opts.stroke || 'var(--seq-4)', 'stop-opacity': '0.28' }));
    lg.appendChild(el('stop', { offset: '100%', 'stop-color': opts.stroke || 'var(--seq-4)', 'stop-opacity': '0' }));
    defs.appendChild(lg);
    svg.appendChild(defs);

    svg.appendChild(el('path', {
      d: dLine + ' L' + xAt(n - 1).toFixed(1) + ' ' + (padT + plotH) + ' L' + xAt(0).toFixed(1) + ' ' + (padT + plotH) + ' Z',
      fill: 'url(#' + gradId + ')', 'class': 'r-area'
    }));

    var path = el('path', {
      d: dLine, stroke: opts.stroke || 'var(--seq-4)', 'class': 'r-line r-line--draw'
    });
    svg.appendChild(path);
    // Length is needed for the draw-on transition; measured after insertion.
    requestAnimationFrame(function () {
      try {
        var len = path.getTotalLength();
        path.style.setProperty('--len', len);
      } catch (e) { path.classList.remove('r-line--draw'); }
    });

    // Markers + hit targets. Only label the endpoints, never every point.
    data.forEach(function (d, i) {
      var cx = xAt(i), cy = yAt(d.value);
      var showDot = n <= 24 || i === 0 || i === n - 1;
      if (showDot) {
        svg.appendChild(el('circle', {
          cx: cx, cy: cy, r: 4.5, fill: opts.stroke || 'var(--seq-4)', 'class': 'r-dot'
        }));
      }
      var hit = el('rect', {
        x: cx - Math.max(10, plotW / n / 2), y: padT,
        width: Math.max(20, plotW / n), height: plotH, fill: 'transparent'
      });
      svg.appendChild(hit);
      hoverable(null, String(d.label), fmt(d.value) + (opts.unit ? ' ' + opts.unit : ''), hit);
    });

    // x labels — thinned so they never collide
    var every = Math.max(1, Math.ceil(n / 12));
    data.forEach(function (d, i) {
      if (i % every && i !== n - 1) return;
      svg.appendChild(el('text', {
        x: xAt(i), y: Hgt - 12, 'text-anchor': 'middle', 'class': 'r-axis-label'
      }, String(d.label)));
    });

    var axis = el('g', { 'class': 'r-axis' });
    axis.appendChild(el('line', { x1: padL, y1: padT + plotH, x2: W - padR, y2: padT + plotH }));
    svg.appendChild(axis);

    return svg;
  }

  // ------------------------------------------------------- chart: scatter
  // Geographic point cloud in plain equirectangular projection, coloured by a
  // magnitude (complexity) using the sequential ramp — one hue, light→dark.
  //
  // At world scale this chart is a lie of omission: roughly half the archive
  // sits inside two degrees of latitude, so ~350 points render as ~40 visible
  // dots and the reader cannot see the structure that matters. The fix is the
  // standard cartographic one — a detail inset. The world panel keeps the
  // international context; the inset re-plots the densest region at ~40x the
  // area, where the same points separate. The inset extent is derived from the
  // data (densest one-degree cell, grown and then tightened onto its contents),
  // not hardcoded to a country, so it follows the archive if the archive moves.

  function densestBox(points) {
    var cells = {}, best = null, k;
    points.forEach(function (p) {
      k = Math.floor(p.lat) + '|' + Math.floor(p.lon);
      cells[k] = (cells[k] || 0) + 1;
    });
    Object.keys(cells).forEach(function (key) {
      if (best === null || cells[key] > cells[best]) best = key;
    });
    if (best === null) return null;

    var parts = best.split('|'), cLat = +parts[0], cLon = +parts[1];
    function within(g0, g1, h0, h1) {
      return points.filter(function (p) {
        return p.lat >= g0 && p.lat <= g1 && p.lon >= h0 && p.lon <= h1;
      });
    }
    // Prefer the modal cell on its own — the tighter the box, the more the
    // cluster separates. Only grow out to the neighbouring degrees when the
    // cell alone is too thin to be worth a panel.
    var inside = within(cLat, cLat + 1, cLon, cLon + 1);
    if (inside.length < 25) inside = within(cLat - 1, cLat + 2, cLon - 1.5, cLon + 2.5);
    // Below this an inset is more clutter than clarification.
    if (inside.length < 12 || inside.length === points.length) return null;

    var lats = inside.map(function (p) { return p.lat; });
    var lons = inside.map(function (p) { return p.lon; });
    var m = 0.08;
    return {
      points: inside,
      n: inside.length,
      lat0: Math.min.apply(null, lats) - m, lat1: Math.max.apply(null, lats) + m,
      lon0: Math.min.apply(null, lons) - m, lon1: Math.max.apply(null, lons) + m
    };
  }

  function scatterGeo(points, opts) {
    opts = opts || {};
    var Hgt = 436, pad = 26, padB = 46, padLeft = 46;
    var plotH = Hgt - pad - padB;

    var inset = densestBox(points);
    // Without an inset the world panel takes the full width, exactly as before.
    var gapX = 34;
    var insetW = inset ? 236 : 0;
    var worldW = W - padLeft - pad - (inset ? insetW + gapX : 0);
    var insetX = padLeft + worldW + gapX;

    var lats = points.map(function (p) { return p.lat; });
    var lons = points.map(function (p) { return p.lon; });
    var minLat = Math.min.apply(null, lats), maxLat = Math.max.apply(null, lats);
    var minLon = Math.min.apply(null, lons), maxLon = Math.max.apply(null, lons);
    var spanLat = (maxLat - minLat) || 1, spanLon = (maxLon - minLon) || 1;

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Geographic scatter plot'
    });

    var deg = function (v, axis, digits) {
      var hemi = axis === 'lat' ? (v >= 0 ? 'N' : 'S') : (v >= 0 ? 'E' : 'W');
      return Math.abs(v).toFixed(digits == null ? 0 : digits) + '°' + hemi;
    };
    var seq = ['var(--seq-1)', 'var(--seq-2)', 'var(--seq-3)', 'var(--seq-4)', 'var(--seq-5)'];

    function plotPoint(p, x, y, r, label, value) {
      var band = Math.min(4, Math.max(0, Math.round(((p.c || 1) - 1) / 9 * 4)));
      // Half-transparent fill so a dense knot reads as density rather than one
      // flat blob; the surface-coloured ring keeps points separable where they
      // still overlap.
      var dot = el('circle', {
        cx: x.toFixed(1), cy: y.toFixed(1), r: r.toFixed(2),
        fill: seq[band], 'fill-opacity': '0.7',
        stroke: 'var(--chart-surface)', 'stroke-width': '0.75'
      });
      svg.appendChild(dot);
      hoverable(dot, label || p.name,
        value || ('complexity ' + p.c + ' · ' + p.lat.toFixed(2) + ', ' + p.lon.toFixed(2)));
    }

    // Records sharing a coordinate to ~100 m are one position, not many.
    function groupByCoord(pts) {
      var seen = {}, out = [];
      pts.forEach(function (p) {
        var k = p.lat.toFixed(3) + ',' + p.lon.toFixed(3);
        if (!seen[k]) {
          seen[k] = { lat: p.lat, lon: p.lon, items: [], rep: p };
          out.push(seen[k]);
        }
        seen[k].items.push(p);
        // The representative carries the group's colour, so let the highest
        // complexity in the group speak for it rather than whichever record
        // happened to be first in the file.
        if ((p.c || 0) > (seen[k].rep.c || 0)) seen[k].rep = p;
      });
      return out;
    }

    // ---- world panel. Graticule with degree labels: without them this reads
    // as an abstract point cloud, and the labels are what make it a projection
    // you can orient in.
    var grid = el('g', { 'class': 'r-grid' });
    for (var i = 0; i <= 4; i++) {
      var f = i / 4;
      var gy = pad + f * plotH;
      var gx = padLeft + f * worldW;
      grid.appendChild(el('line', { x1: padLeft, y1: gy, x2: padLeft + worldW, y2: gy }));
      grid.appendChild(el('line', { x1: gx, y1: pad, x2: gx, y2: pad + plotH }));
      svg.appendChild(el('text', {
        x: padLeft - 9, y: gy + 3.5, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, deg(maxLat - f * spanLat, 'lat')));
      svg.appendChild(el('text', {
        x: gx, y: pad + plotH + 18, 'text-anchor': 'middle', 'class': 'r-axis-label'
      }, deg(minLon + f * spanLon, 'lon')));
    }
    svg.appendChild(grid);

    var wx = function (lon) { return padLeft + ((lon - minLon) / spanLon) * worldW; };
    var wy = function (lat) { return pad + (1 - (lat - minLat) / spanLat) * plotH; };
    points.forEach(function (p) { plotPoint(p, wx(p.lon), wy(p.lat), 4); });

    svg.appendChild(el('text', {
      x: padLeft, y: Hgt - 10, 'class': 'r-axis-label'
    }, 'World · all ' + points.length + ' geolocated formations'));

    // ---- detail inset
    if (inset) {
      var iLatSpan = inset.lat1 - inset.lat0, iLonSpan = inset.lon1 - inset.lon0;
      // Scale longitude by cos(mid-latitude) so the inset is not stretched
      // sideways — at 51°N a degree of longitude is only ~0.63 of a degree of
      // latitude on the ground, and an unscaled box distorts the cluster shape.
      var midLat = (inset.lat0 + inset.lat1) / 2;
      var lonUnits = iLonSpan * Math.cos(midLat * Math.PI / 180);
      var scale = Math.min(insetW / lonUnits, plotH / iLatSpan);
      var mapW = lonUnits * scale, mapH = iLatSpan * scale;
      var mx = insetX + (insetW - mapW) / 2, my = pad + (plotH - mapH) / 2;

      // Callout on the world panel: the rectangle the inset magnifies, plus
      // leaders to the inset frame so the relationship is not left implied.
      var cx0 = wx(inset.lon0), cx1 = wx(inset.lon1);
      var cy0 = wy(inset.lat1), cy1 = wy(inset.lat0);
      // At world scale the box is often under two pixels across. Floor it at a
      // size that can actually be seen; the caption carries the true extent.
      var callW = Math.max(cx1 - cx0, 14), callH = Math.max(cy1 - cy0, 14);
      var callX = (cx0 + cx1) / 2 - callW / 2, callY = (cy0 + cy1) / 2 - callH / 2;

      svg.appendChild(el('rect', {
        x: callX.toFixed(1), y: callY.toFixed(1),
        width: callW.toFixed(1), height: callH.toFixed(1),
        fill: 'none', stroke: 'var(--signal)', 'stroke-width': '1.25',
        'stroke-dasharray': '3 3'
      }));
      [[callY, my], [callY + callH, my + mapH]].forEach(function (pair) {
        svg.appendChild(el('line', {
          x1: (callX + callW).toFixed(1), y1: pair[0].toFixed(1),
          x2: mx.toFixed(1), y2: pair[1].toFixed(1),
          stroke: 'var(--signal)', 'stroke-width': '1',
          'stroke-opacity': '0.42', 'stroke-dasharray': '3 4'
        }));
      });

      svg.appendChild(el('rect', {
        x: mx.toFixed(1), y: my.toFixed(1),
        width: mapW.toFixed(1), height: mapH.toFixed(1),
        fill: 'var(--chart-surface)', 'fill-opacity': '0.55',
        stroke: 'var(--signal)', 'stroke-width': '1.25'
      }));

      var igrid = el('g', { 'class': 'r-grid' });
      for (i = 1; i <= 3; i++) {
        igrid.appendChild(el('line', {
          x1: mx, y1: my + (i / 4) * mapH, x2: mx + mapW, y2: my + (i / 4) * mapH
        }));
        igrid.appendChild(el('line', {
          x1: mx + (i / 4) * mapW, y1: my, x2: mx + (i / 4) * mapW, y2: my + mapH
        }));
      }
      svg.appendChild(igrid);

      // Zoom alone does not finish the job: a large minority of the archive
      // shares EXACT coordinates with another record — many entries carry a
      // site-level or rounded fix rather than a field-level one, so 146 points
      // can sit on 87 distinct positions. No magnification separates those.
      // The inset therefore groups by coordinate and sizes the symbol by
      // count, which stops the chart implying locations it does not have.
      var groups = groupByCoord(inset.points);
      // Big groups behind, singles in front, so a single formation sharing a
      // village with fifteen others is still hoverable.
      groups.sort(function (a, b) { return b.items.length - a.items.length; });
      groups.forEach(function (grp) {
        var x = mx + ((grp.lon - inset.lon0) / iLonSpan) * mapW;
        var y = my + (1 - (grp.lat - inset.lat0) / iLatSpan) * mapH;
        // Area proportional to count, which is the only sizing that does not
        // mislead the eye — hence the square root on the radius.
        var r = Math.min(15, 4.5 * Math.sqrt(grp.items.length));
        plotPoint(grp.rep, x, y, r, grp.items.length > 1
          ? grp.items.length + ' formations · ' + grp.lat.toFixed(3) + ', ' + grp.lon.toFixed(3)
          : null, grp.items.length > 1
          ? grp.items.slice(0, 4).map(function (q) { return q.name; }).join(' · ') +
            (grp.items.length > 4 ? ' · +' + (grp.items.length - 4) + ' more' : '')
          : null);
      });

      // The magnification factor is the honest headline for an inset: without
      // it the reader has no way to judge how much the world panel compressed.
      // Quoted linearly, the way a map inset is conventionally read — the area
      // ratio is the square of this and reads as a typo.
      // Measured against the box's TRUE extent, not the floored drawing size,
      // or the quoted factor is smaller than the magnification actually is.
      var mag = Math.round(Math.sqrt(
        (mapW / Math.max(cx1 - cx0, 0.001)) * (mapH / Math.max(cy1 - cy0, 0.001))));
      svg.appendChild(el('text', {
        x: insetX + insetW / 2, y: pad - 8, 'text-anchor': 'middle', 'class': 'r-axis-label'
      }, deg(inset.lat0, 'lat', 1) + '–' + deg(inset.lat1, 'lat', 1) + ' · ' +
         deg(inset.lon0, 'lon', 1) + '–' + deg(inset.lon1, 'lon', 1)));
      svg.appendChild(el('text', {
        x: insetX + insetW / 2, y: Hgt - 10, 'text-anchor': 'middle', 'class': 'r-axis-label'
      }, 'Detail · ×' + mag + ' scale · ' + inset.n + ' formations at ' +
         groups.length + ' distinct coordinates'));

      // Size key. Without it the reader has no way to decode a bubble, and a
      // proportional-symbol map without a key is just a prettier lie.
      var keyY = my + mapH - 16, keyX = mx + 14;
      [1, 4, 12].forEach(function (n, ki) {
        var kr = Math.min(15, 4.5 * Math.sqrt(n));
        svg.appendChild(el('circle', {
          cx: keyX, cy: keyY, r: kr.toFixed(2),
          fill: 'none', stroke: 'var(--chart-axis)', 'stroke-width': '1'
        }));
        svg.appendChild(el('text', {
          x: keyX, y: keyY - kr - 4, 'text-anchor': 'middle', 'class': 'r-axis-label'
        }, String(n)));
        keyX += kr + (ki < 2 ? Math.min(15, 4.5 * Math.sqrt([1, 4, 12][ki + 1])) + 10 : 0);
      });
    }

    return svg;
  }

  // ------------------------------------ chart: hypothesis confidence bars
  // Ordinal 0-5 confidence per hypothesis. Categorical hues in fixed order
  // (each hypothesis is a distinct entity), and the level is ALSO printed as
  // text so identity never rests on colour alone.

  function confidenceBars(items, scaleMax) {
    // padL has to clear the longest "H3 · Electromagnetic / plasma vortex"
    // label — text-anchor:end means an undersized gutter clips off the left
    // edge rather than wrapping.
    var rowH = 34, gap = 10, padL = 252, padR = 104, padT = 6;
    var Hgt = padT + items.length * (rowH + gap);
    var plotW = W - padL - padR;

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': 'Confidence level by hypothesis'
    });

    // step ticks
    var grid = el('g', { 'class': 'r-grid' });
    for (var s = 0; s <= scaleMax; s++) {
      var x = padL + (s / scaleMax) * plotW;
      grid.appendChild(el('line', { x1: x, y1: padT, x2: x, y2: Hgt - 6 }));
    }
    svg.appendChild(grid);

    items.forEach(function (it, i) {
      var y = padT + i * (rowH + gap);
      var w = Math.max(3, ((it.score || 0) / scaleMax) * plotW);

      svg.appendChild(el('text', {
        x: padL - 12, y: y + rowH / 2 + 4, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, it.id + ' · ' + it.name));

      var bar = el('rect', {
        x: padL, y: y, width: w, height: rowH, rx: 4,
        fill: catVar(i), 'class': 'r-bar r-barh--grow'
      });
      bar.style.transitionDelay = (i * 60) + 'ms';
      svg.appendChild(bar);

      svg.appendChild(el('text', {
        x: padL + w + 10, y: y + rowH / 2 + 4, 'class': 'r-value-label'
      }, it.label || '—'));

      hoverable(bar, it.id + ' ' + it.name, (it.label || '—') + ' (' + (it.score == null ? '—' : it.score) + '/' + scaleMax + ')');
    });

    return svg;
  }

  // ------------------------------------------------- chart: stacked share bar
  // One whole, split into parts. Used where the parts sum to something
  // meaningful (all formations, all leads) and the *proportions* are the point
  // — a bar chart of the same numbers reads as four unrelated quantities.
  //
  // Every segment wide enough to hold text is labelled inside itself, so the
  // chart survives without the legend and without colour vision.

  function stackedBar(segments, opts) {
    opts = opts || {};
    var Hgt = 96, padT = 10, barH = 52;
    var total = segments.reduce(function (a, s) { return a + s.value; }, 0) || 1;

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Proportional breakdown'
    });

    var x = 0;
    segments.forEach(function (s, i) {
      var w = (s.value / total) * W;
      var share = 100 * s.value / total;
      var g = el('g', { 'class': 'r-seg' });
      g.style.transitionDelay = (i * 70) + 'ms';

      g.appendChild(el('rect', {
        x: x, y: padT, width: Math.max(1, w - 2), height: barH,
        rx: 3, fill: s.color, 'class': 'r-seg-rect'
      }));

      // 46 units is roughly where "12.3%" stops fitting.
      if (w > 46) {
        g.appendChild(el('text', {
          x: x + w / 2 - 1, y: padT + barH / 2 + 5,
          'text-anchor': 'middle', 'class': 'r-seg-label'
        }, fmt(share, share < 10 ? 1 : 0) + '%'));
      }
      if (w > 120) {
        g.appendChild(el('text', {
          x: x + w / 2 - 1, y: padT + barH + 20,
          'text-anchor': 'middle', 'class': 'r-axis-label'
        }, s.label));
      }
      hoverable(g, s.label, fmt(s.value) + ' · ' + fmt(share, 1) + '%');
      svg.appendChild(g);
      x += w;
    });

    return svg;
  }

  // ------------------------------------------------------- chart: heatmap
  // Two categorical axes, one magnitude. Rows are normalised against their own
  // maximum rather than a global one: the decades hold wildly different record
  // counts (3 formations in the 1970s against 108 in the 2000s), and on a
  // global scale every early row would render as a uniform blank. The question
  // this chart answers is what shape each decade's season has, not how many
  // formations it holds — that number is printed alongside the row label.

  function heatmap(rows, colLabels, opts) {
    opts = opts || {};
    var padL = 92, padT = 26, cellH = 30, gap = 3;
    var cols = colLabels.length;
    var cellW = (W - padL - 8) / cols;
    var Hgt = padT + rows.length * (cellH + gap) + 8;

    var svg = el('svg', {
      'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
      role: 'img', 'aria-label': opts.ariaLabel || 'Heatmap'
    });

    colLabels.forEach(function (c, ci) {
      svg.appendChild(el('text', {
        x: padL + ci * cellW + cellW / 2, y: padT - 10,
        'text-anchor': 'middle', 'class': 'r-axis-label'
      }, c));
    });

    rows.forEach(function (row, ri) {
      var y = padT + ri * (cellH + gap);
      var rowMax = Math.max.apply(null, row.values) || 1;

      svg.appendChild(el('text', {
        x: padL - 12, y: y + cellH / 2 + 4, 'text-anchor': 'end', 'class': 'r-axis-label'
      }, row.label));

      row.values.forEach(function (v, ci) {
        var step = v === 0 ? 0 : Math.min(5, Math.ceil((v / rowMax) * 5));
        var cell = el('rect', {
          x: padL + ci * cellW, y: y,
          width: cellW - gap, height: cellH, rx: 3,
          fill: step === 0 ? 'var(--panel-soft)' : 'var(--seq-' + step + ')',
          'class': 'r-cell'
        });
        cell.style.transitionDelay = (ri * 40 + ci * 12) + 'ms';
        svg.appendChild(cell);
        hoverable(cell, row.label + ' · ' + colLabels[ci],
          fmt(v) + ' of ' + fmt(row.n) + ' (' + fmt(100 * v / (row.n || 1), 1) + '%)');
      });
    });

    return svg;
  }

  // --------------------------------------------------- chart: sparkline grid
  // Several one-number-per-step series that share an x axis but not a y scale
  // (a 0-10 complexity score against a 0-100 percentage). Plotting them on one
  // pair of axes would need either a second axis or a normalisation that makes
  // the numbers unreadable; small multiples keep each on its own honest scale
  // and let the eye compare *shapes*, which is the actual question.

  function sparkGrid(items) {
    var wrap = h('div', 'r-sparks');

    items.forEach(function (item) {
      var cell = h('div', 'r-spark');
      cell.appendChild(h('div', 'r-spark-label', item.label));

      var vals = item.points.map(function (p) { return p.value == null ? 0 : p.value; });
      var lo = Math.min.apply(null, vals);
      var hi = Math.max.apply(null, vals);
      if (hi === lo) { hi = lo + 1; }
      var sw = 260, sh = 62, sp = 6;
      var n = vals.length;
      var xAt = function (i) { return sp + (n === 1 ? sw / 2 : (i / (n - 1)) * (sw - sp * 2)); };
      var yAt = function (v) { return sp + (1 - (v - lo) / (hi - lo)) * (sh - sp * 2); };

      var svg = el('svg', {
        'class': 'r-spark-svg', viewBox: '0 0 ' + sw + ' ' + sh,
        preserveAspectRatio: 'none',
        role: 'img', 'aria-label': item.label + ' by ' + (item.xName || 'step')
      });

      var d = vals.map(function (v, i) {
        return (i ? 'L' : 'M') + xAt(i).toFixed(1) + ' ' + yAt(v).toFixed(1);
      }).join(' ');
      svg.appendChild(el('path', {
        d: d + ' L' + xAt(n - 1).toFixed(1) + ' ' + (sh - sp) + ' L' + xAt(0).toFixed(1) + ' ' + (sh - sp) + ' Z',
        fill: item.color || 'var(--seq-3)', 'fill-opacity': '0.14', stroke: 'none'
      }));
      svg.appendChild(el('path', {
        d: d, fill: 'none', stroke: item.color || 'var(--seq-4)',
        'stroke-width': 2, 'stroke-linejoin': 'round', 'class': 'r-spark-line'
      }));

      vals.forEach(function (v, i) {
        var dot = el('circle', {
          cx: xAt(i), cy: yAt(v), r: i === n - 1 ? 4 : 2.6,
          fill: item.color || 'var(--seq-4)'
        });
        var hit = el('circle', { cx: xAt(i), cy: yAt(v), r: 11, fill: 'transparent' });
        svg.appendChild(dot);
        svg.appendChild(hit);
        hoverable(dot, item.points[i].label + ' · ' + item.label,
          (item.format ? item.format(v) : fmt(v, 1)));
      });

      cell.appendChild(svg);

      var foot = h('div', 'r-spark-foot');
      foot.appendChild(h('span', 'r-spark-range', item.points[0].label + ' → ' + item.points[n - 1].label));
      foot.appendChild(h('span', 'r-spark-now',
        item.format ? item.format(vals[n - 1]) : fmt(vals[n - 1], 1)));
      cell.appendChild(foot);
      wrap.appendChild(cell);
    });

    return wrap;
  }

  // ---------------------------------------------------------- rank list (HTML)
  // A ranked set of named things, each with a magnitude. Built as HTML rather
  // than SVG because the names are the content here — real place and formation
  // names, long and unpredictable, which have to wrap. In an SVG chart they'd
  // either be truncated or force a gutter wide enough to squash the bars.

  function rankList(items, opts) {
    opts = opts || {};
    var max = Math.max.apply(null, items.map(function (i) { return i.value; })) || 1;
    var wrap = h('ol', 'r-rank');

    items.forEach(function (item, i) {
      var li = h('li', 'r-rank-row');
      li.style.transitionDelay = (i * 40) + 'ms';

      var head = h('div', 'r-rank-head');
      head.appendChild(h('span', 'r-rank-name', item.label));
      head.appendChild(h('span', 'r-rank-value',
        opts.format ? opts.format(item.value) : fmt(item.value)));
      li.appendChild(head);

      if (item.sub) li.appendChild(h('span', 'r-rank-sub', item.sub));

      var track = h('span', 'r-rank-track');
      var fill = h('span', 'r-rank-fill');
      fill.style.width = (100 * item.value / max) + '%';
      fill.style.background = opts.colorByIndex ? catVar(i) : (opts.color || 'var(--seq-3)');
      track.appendChild(fill);
      li.appendChild(track);

      wrap.appendChild(li);
    });

    return wrap;
  }

  // -------------------------------------------------------------- building

  function legend(entries) {
    var wrap = h('div', 'r-legend');
    entries.forEach(function (e) {
      var item = h('span', 'r-legend-item');
      var sw = h('span', 'r-legend-swatch');
      sw.style.background = e.color;
      item.appendChild(sw);
      item.appendChild(document.createTextNode(e.label));
      wrap.appendChild(item);
    });
    return wrap;
  }

  // Every chart ships a table view — the accessible fallback and the answer to
  // "what exactly is that bar".
  function tableView(cols, rows) {
    var wrap = h('div', 'r-table-wrap');
    wrap.hidden = true;
    var t = h('table', 'r-table');
    var thead = document.createElement('thead');
    var tr = document.createElement('tr');
    cols.forEach(function (c) { tr.appendChild(h('th', null, c)); });
    thead.appendChild(tr);
    t.appendChild(thead);
    var tb = document.createElement('tbody');
    rows.forEach(function (r) {
      var row = document.createElement('tr');
      r.forEach(function (cell) { row.appendChild(h('td', null, String(cell))); });
      tb.appendChild(row);
    });
    t.appendChild(tb);
    wrap.appendChild(t);

    var btn = h('button', 'r-table-toggle', 'Show data table');
    btn.type = 'button';
    btn.setAttribute('aria-expanded', 'false');
    btn.addEventListener('click', function () {
      var open = !wrap.hidden;
      wrap.hidden = open;
      btn.setAttribute('aria-expanded', String(!open));
      btn.textContent = open ? 'Show data table' : 'Hide data table';
    });

    var frag = document.createDocumentFragment();
    frag.appendChild(btn);
    frag.appendChild(wrap);
    return frag;
  }

  function deltaChip(value, unit, opts) {
    opts = opts || {};
    if (value == null || isNaN(value)) return null;
    var dir = value > 0 ? 'up' : value < 0 ? 'down' : 'flat';
    // Direction is spelled out; the colour is reinforcement, not the signal.
    var arrow = dir === 'up' ? '▲' : dir === 'down' ? '▼' : '■';
    var word = dir === 'flat' ? 'no change' :
      (dir === 'up' ? '+' : '') + fmt(value, opts.digits == null ? 1 : opts.digits) + (unit || '');
    var chip = h('span', 'r-delta r-delta--' + dir);
    chip.appendChild(document.createTextNode(arrow + ' ' + word + ' vs last week'));
    return chip;
  }

  function card(opts) {
    var c = h('article', 'r-card');
    var head = h('div', 'r-card-head');
    if (opts.kicker) head.appendChild(h('p', 'r-kicker', opts.kicker));
    head.appendChild(h('h2', 'r-title', opts.title));
    c.appendChild(head);

    if (opts.hero) {
      var fig = h('div', 'r-hero-figure');
      fig.appendChild(h('span', 'r-hero-value', opts.hero.value));
      if (opts.hero.unit) fig.appendChild(h('span', 'r-hero-unit', opts.hero.unit));
      if (opts.hero.delta) fig.appendChild(opts.hero.delta);
      c.appendChild(fig);
    }

    if (opts.chart) {
      var scroll = h('div', 'r-chart-scroll');
      scroll.appendChild(opts.chart);
      c.appendChild(scroll);
    }
    // `block` is for HTML-built content (rank lists, sparkline grids, the
    // session log) — it reflows rather than scrolling sideways, so it must not
    // go inside .r-chart-scroll the way an SVG chart does.
    if (opts.block) c.appendChild(opts.block);
    if (opts.legend) c.appendChild(opts.legend);
    if (opts.reading) c.appendChild(h('p', 'r-reading', opts.reading));
    if (opts.table) c.appendChild(opts.table);
    return c;
  }

  function tiles(items) {
    var wrap = h('div', 'r-tiles');
    items.forEach(function (t) {
      var tile = h('div', 'r-tile');
      tile.appendChild(h('div', 'r-tile-label', t.label));
      tile.appendChild(h('div', 'r-tile-value', t.value));
      if (t.sub) tile.appendChild(h('div', 'r-tile-sub', t.sub));
      wrap.appendChild(tile);
    });
    return wrap;
  }

  // ------------------------------------------------------------------ tabs

  var TABS = [
    { id: 'geography', label: 'Geography', build: buildGeography },
    { id: 'time', label: 'Time & season', build: buildTime },
    { id: 'geometry', label: 'Geometry & scale', build: buildGeometry },
    { id: 'evidence', label: 'Evidence', build: buildEvidence },
    { id: 'hypotheses', label: 'Hypotheses', build: buildHypotheses },
    { id: 'programme', label: 'Research log', build: buildProgramme },
    { id: 'health', label: 'Dataset health', build: buildHealth }
  ];

  function buildGeography() {
    var g = R.geography, m = R.metrics, out = [];

    out.push(card({
      kicker: 'Distribution',
      title: 'Where formations are reported',
      hero: {
        value: pct(m.ukPct),
        unit: 'of all recorded formations are in the UK',
        delta: null
      },
      chart: barsH(g.countries, {
        ariaLabel: 'Formations by country',
        labelWidth: 150,
        unit: 'formations'
      }),
      reading: 'The archive is heavily UK-weighted, and that is a fact about the ' +
        'record rather than necessarily about the phenomenon: the UK has the ' +
        'densest reporting infrastructure, the longest-running documentation ' +
        'groups, and the most active aerial photographers. Countries in the ' +
        '"Other" bucket each contribute fewer than eleven formations.',
      table: tableView(['Country', 'Formations'],
        g.countries.map(function (d) { return [d.label, d.value]; }))
    }));

    out.push(card({
      kicker: 'Concentration',
      title: 'Within the UK, one county dominates',
      hero: {
        value: pct(m.wiltshirePct),
        unit: 'of the entire archive is Wiltshire alone',
        delta: deltaChip(R.deltas.wiltshirePct, 'pp')
      },
      chart: barsH(g.ukRegions, {
        ariaLabel: 'UK formations by county',
        labelWidth: 150,
        unit: 'formations'
      }),
      reading: 'Wiltshire accounts for more formations than every non-UK country ' +
        'combined. The county sits on chalk downland with large open fields and ' +
        'a dense concentration of neolithic monuments — and it is also where ' +
        'nearly all dedicated crop circle researchers are based, so observation ' +
        'effort and formation count are hard to separate here.',
      table: tableView(['County', 'Formations'],
        g.ukRegions.map(function (d) { return [d.label, d.value]; }))
    }));

    if (g.points && g.points.length) {
      out.push(card({
        kicker: 'Spatial',
        title: 'Every geolocated formation, plotted',
        chart: scatterGeo(g.points, { ariaLabel: 'Formation locations by latitude and longitude' }),
        legend: legend([
          { label: 'complexity 1–2', color: 'var(--seq-1)' },
          { label: '3–4', color: 'var(--seq-2)' },
          { label: '5–6', color: 'var(--seq-3)' },
          { label: '7–8', color: 'var(--seq-4)' },
          { label: '9–10', color: 'var(--seq-5)' }
        ]),
        reading: 'All ' + fmt(g.points.length) + ' geolocated formations are plotted ' +
          'by latitude and longitude, shaded by complexity score. On the world ' +
          'panel far fewer than ' + fmt(g.points.length) + ' dots are visible, ' +
          'because most of them land on top of each other: roughly half the ' +
          'archive sits inside about two degrees of latitude in southern England, ' +
          'and at world scale those hundreds of formations collapse into a single ' +
          'smudge. The amber box marks that knot, and the panel beside it re-plots ' +
          'the same points at map scale, where most of them separate. The outliers ' +
          'on the world panel are the international record. ' +
          'Zoom alone is not enough, though: in the detail panel each symbol is ' +
          'sized by how many records share that coordinate, and a good number of ' +
          'them stack. Those are not formations in the same field — they are ' +
          'records carrying a village- or site-level fix rather than a surveyed ' +
          'one, which is a dataset limitation rather than a finding. Hover any ' +
          'symbol for the names behind it. The engine currently resolves ' +
          fmt(m.clusters) + ' distinct spatial clusters.'
      }));
    }

    var near = g.nearAncientSite;
    out.push(card({
      kicker: 'Proximity',
      title: 'Distance to the nearest ancient site',
      chart: null,
      hero: {
        value: pct(m.nearSitePct),
        unit: 'appear near a known ancient site',
        delta: deltaChip(R.deltas.nearSitePct, 'pp')
      },
      reading: 'Of ' + fmt(near.near + near.far) + ' formations, ' + fmt(near.near) +
        ' fall within the engine\'s "near ancient site" threshold and ' + fmt(near.far) +
        ' do not. The difference in mean distance tests as statistically significant ' +
        '(t = ' + fmt(near.tStat, 2) + ', p = ' + fmt(near.pValue, 4) + '), which is ' +
        'the strongest geographic signal in the dataset — though proximity to ' +
        'monuments and proximity to Wiltshire chalk downland are themselves ' +
        'correlated, so this is not yet an independent finding.'
    }));

    out[out.length - 1].insertBefore(
      tiles([
        { label: 'Near a site', value: fmt(near.near), sub: 'formations' },
        { label: 'Not near', value: fmt(near.far), sub: 'formations' },
        { label: 'Mean distance', value: fmt(near.meanDistKm, 2), sub: 'km to nearest site' },
        { label: 'Significance', value: 'p ' + fmt(near.pValue, 3), sub: 't = ' + fmt(near.tStat, 2) }
      ]),
      out[out.length - 1].querySelector('.r-reading')
    );

    var s = R.sites;
    if (s && s.ancientSites && s.ancientSites.length) {
      out.push(card({
        kicker: 'Named sites',
        title: 'Which monuments turn up more than once',
        block: rankList(s.ancientSites, {
          color: 'var(--cat-2)',
          format: function (v) { return fmt(v) + (v === 1 ? ' formation' : ' formations'); }
        }),
        reading: 'Only ' + pct(s.namedSitePct) + ' of records name the monument they ' +
          'sit beside, so this is a ranking within a small, self-selected slice — ' +
          'the records that name a site are disproportionately the famous ones. ' +
          'Read it as "which sites researchers write down", not as a league table ' +
          'of monument attraction. The Avebury complex — Silbury Hill, Avebury ' +
          'itself, the West Kennett barrow, the Hackpen horse — accounts for most ' +
          'of the top of this list, and those are all within a few miles of each ' +
          'other on the same stretch of Wiltshire chalk.',
        table: tableView(['Site', 'Formations'],
          s.ancientSites.map(function (d) { return [d.label, d.value]; }))
      }));
    }

    if (s && s.repeatFields && s.repeatFields.length) {
      out.push(card({
        kicker: 'Repetition',
        title: 'Fields that get hit more than once',
        hero: {
          value: fmt(s.repeatFieldTotal),
          unit: 'locations carry more than one formation',
          delta: null
        },
        block: rankList(s.repeatFields, { color: 'var(--seq-3)', format: function (v) { return fmt(v) + '×'; } }),
        reading: 'Recurrence at a single named location is one of the few patterns ' +
          'in the archive that a purely random process would not produce — but it ' +
          'is also exactly what you would expect from a small number of ' +
          'well-watched, easily-accessed fields near the roads researchers drive. ' +
          'Note too that some entries here are generic ("Barley field", "Wheat ' +
          'plantation") rather than real place names: those are a data-quality ' +
          'artifact of sparse location detail, not a site that keeps recurring.',
        table: tableView(['Location', 'Formations'],
          s.repeatFields.map(function (d) { return [d.label, d.value]; }))
      }));
    }

    return out;
  }

  function buildTime() {
    var t = R.time, out = [];

    out.push(card({
      kicker: 'Seasonality',
      title: 'Formations follow the harvest',
      hero: {
        value: pct(t.summerPct),
        unit: 'of all formations appear June–August',
        delta: null
      },
      chart: barsV(t.perMonth, {
        ariaLabel: 'Formations by month of year',
        unit: 'formations',
        emphasis: function (d) { return d.month >= 6 && d.month <= 8; },
        emphasisFill: 'var(--seq-4)',
        fill: 'var(--seq-2)'
      }),
      legend: legend([
        { label: 'June–August', color: 'var(--seq-4)' },
        { label: 'rest of year', color: 'var(--seq-2)' }
      ]),
      reading: 'This is the least mysterious pattern in the archive and the most ' +
        'important one to state plainly: formations appear when there is standing ' +
        'crop tall enough to lay down. The season opens as winter wheat reaches ' +
        'height and closes at harvest. Any explanation — human or otherwise — has ' +
        'to operate inside that window, so seasonality discriminates between ' +
        'hypotheses far less than it first appears to.',
      table: tableView(['Month', 'Formations'],
        t.perMonth.map(function (d) { return [d.label, d.value]; }))
    }));

    if (t.perYear && t.perYear.length) {
      out.push(card({
        kicker: 'Over time',
        title: 'Reported formations per year',
        chart: lineChart(t.perYear, {
          ariaLabel: 'Formations reported per year since 1970',
          unit: 'formations',
          stroke: 'var(--seq-4)'
        }),
        reading: 'The record rises sharply through the 1990s — the period when crop ' +
          'circles became a mass-media subject and dedicated documentation groups ' +
          'formed — then settles. Read this as a curve of documentation effort at ' +
          'least as much as one of formation frequency: the archive can only ' +
          'contain what somebody recorded. The apparent fall in the most recent ' +
          'year is normally just the current season still being incomplete.',
        table: tableView(['Year', 'Formations'],
          t.perYear.map(function (d) { return [d.label, d.value]; }))
      }));
    }

    var e = R.eras || {};
    if (e.monthByDecade && e.monthByDecade.length) {
      out.push(card({
        kicker: 'Season shape',
        title: 'Has the season itself moved?',
        chart: heatmap(e.monthByDecade, e.monthNames, {
          ariaLabel: 'Formations by month, one row per decade, each row shaded against its own peak'
        }),
        legend: legend([
          { label: 'row minimum', color: 'var(--seq-1)' },
          { label: '', color: 'var(--seq-2)' },
          { label: '', color: 'var(--seq-3)' },
          { label: '', color: 'var(--seq-4)' },
          { label: 'row peak', color: 'var(--seq-5)' }
        ]),
        reading: 'Each row is one decade, shaded against its own busiest month ' +
          'rather than against the whole archive — the decades hold very ' +
          'different record counts, so a shared scale would render the thin rows ' +
          'blank and tell you nothing. Only decades with at least five ' +
          'month-dated records appear at all, which is why the record starts here ' +
          'in the 1990s rather than in the 1970s. What this asks is whether the ' +
          'shape of the season has shifted. It broadly has not: the July–August ' +
          'core sits in the middle of every row. What ' +
          'does change is the spread — later decades carry more non-summer ' +
          'entries, which most likely tracks the archive picking up southern ' +
          'hemisphere and out-of-season reports rather than the season widening.',
        table: tableView(['Decade'].concat(e.monthNames),
          e.monthByDecade.map(function (r) { return [r.label].concat(r.values); }))
      }));
    }

    if (e.decades && e.decades.length > 2) {
      out.push(card({
        kicker: 'By decade',
        title: 'Every headline number, cut by era',
        block: sparkGrid([
          {
            label: 'Records per decade', color: 'var(--cat-3)', xName: 'decade',
            points: e.decades.map(function (d) { return { label: d.label, value: d.n }; }),
            format: function (v) { return fmt(v); }
          },
          {
            label: 'Mean complexity', color: 'var(--cat-1)', xName: 'decade',
            points: e.decades.map(function (d) { return { label: d.label, value: d.meanComplexity }; }),
            format: function (v) { return fmt(v, 2) + ' / 10'; }
          },
          {
            label: 'Sacred geometry', color: 'var(--cat-6)', xName: 'decade',
            points: e.decades.map(function (d) { return { label: d.label, value: d.sgPct }; }),
            format: function (v) { return pct(v); }
          },
          {
            label: 'UK share', color: 'var(--cat-2)', xName: 'decade',
            points: e.decades.map(function (d) { return { label: d.label, value: d.ukPct }; }),
            format: function (v) { return pct(v); }
          }
        ]),
        reading: 'The archive\'s single-number statistics are averages over three ' +
          'and a half centuries of very unevenly distributed records, so it is ' +
          'worth seeing what they look like decade by decade. Only decades ' +
          'holding at least ten records are plotted — a percentage over three ' +
          'formations is noise wearing the costume of a trend. Two things stand ' +
          'out. Mean complexity and the sacred-geometry rate both peak in the ' +
          '1990s and drift down afterwards — the opposite of the popular claim ' +
          'that formations have grown more elaborate, and consistent with the ' +
          'flat regression on the Geometry tab. And the UK share swings hard: ' +
          'high in the 1990s, down through the 2010s as European and North ' +
          'American reporting picked up, then back up in the 2020s, which is far ' +
          'more likely to be about who is currently documenting than about where ' +
          'formations are appearing. Each panel is on its own scale.',
        table: tableView(['Decade', 'Records', 'Mean complexity', 'Sacred geometry', 'UK share', 'Mean diameter'],
          e.decades.map(function (d) {
            return [d.label, d.n, fmt(d.meanComplexity, 2), pct(d.sgPct), pct(d.ukPct),
              d.meanDiameterM == null ? '—' : fmt(d.meanDiameterM, 1) + ' m'];
          }))
      }));
    }

    return out;
  }

  function buildGeometry() {
    var g = R.geometry, out = [];
    var tr = g.complexityTrend || {};

    out.push(card({
      kicker: 'Complexity',
      title: 'Most formations are simple',
      hero: {
        value: fmt(g.meanComplexity, 2),
        unit: 'mean complexity score, out of 10',
        delta: deltaChip(R.deltas.meanComplexity, '', { digits: 2 })
      },
      chart: barsV(g.complexity, {
        ariaLabel: 'Distribution of complexity scores',
        unit: 'formations',
        fill: 'var(--seq-3)'
      }),
      reading: 'The distribution is strongly weighted toward the low end — the ' +
        'archive is mostly plain circles and simple rings. The elaborate ' +
        'fractal and pictogram formations that dominate public perception of the ' +
        'subject are a small minority of the actual record, which is worth ' +
        'holding onto when assessing any explanation built on the complex ones.',
      table: tableView(['Complexity score', 'Formations'],
        g.complexity.map(function (d) { return [d.label, d.value]; }))
    }));

    out.push(card({
      kicker: 'Form',
      title: 'Geometric type breakdown',
      chart: barsH(g.types, {
        ariaLabel: 'Formations by geometric type',
        labelWidth: 190,
        unit: 'formations'
      }),
      reading: 'Simple circles outnumber every other form several times over. ' +
        'The named categories below them — pictograms, fractal spirals, ' +
        'triangular constructions — are where the archive\'s more structurally ' +
        'interesting cases sit.',
      table: tableView(['Geometric type', 'Formations'],
        g.types.map(function (d) { return [d.label, d.value]; }))
    }));

    out.push(card({
      kicker: 'Encoded features',
      title: 'Mathematical structure in the record',
      chart: barsH(g.encoded, {
        ariaLabel: 'Count of formations flagged with each encoded feature',
        labelWidth: 170,
        colorByIndex: true,
        unit: 'formations'
      }),
      reading: 'Counts of formations the engine has flagged as containing each ' +
        'feature. These flags come from the source records and the engine\'s own ' +
        'scoring rather than from independent re-measurement, so treat them as ' +
        'a research index — a list of where to look — rather than as verified ' +
        'mathematical claims about each formation.',
      table: tableView(['Feature', 'Formations'],
        g.encoded.map(function (d) { return [d.label, d.value]; }))
    }));

    out.push(card({
      kicker: 'Trend',
      title: 'Are formations getting more complex over time?',
      reading: 'Not detectably. Fitting complexity against year gives a slope of ' +
        fmt(tr.slopePerYear, 4) + ' points per year with R² = ' + fmt(tr.r2, 3) +
        ' and p = ' + fmt(tr.pValue, 3) + '. An R² that low means year explains ' +
        'essentially none of the variation in complexity, and the p-value gives ' +
        'no grounds to reject chance. The popular narrative that formations have ' +
        'grown steadily more elaborate is not supported by this dataset.'
    }));

    out[out.length - 1].insertBefore(
      tiles([
        { label: 'Slope', value: fmt(tr.slopePerYear, 4), sub: 'complexity / year' },
        { label: 'R²', value: fmt(tr.r2, 3), sub: 'variance explained' },
        { label: 'p-value', value: fmt(tr.pValue, 3), sub: tr.pValue > 0.05 ? 'not significant' : 'significant' },
        { label: 'Mean diameter', value: fmt(g.meanDiameterM, 1), sub: 'metres' }
      ]),
      out[out.length - 1].querySelector('.r-reading')
    );

    // -- scale ------------------------------------------------------------
    var sc = R.scale;
    if (sc && sc.buckets) {
      out.push(card({
        kicker: 'Scale',
        title: 'How big are these things',
        hero: {
          value: fmt(sc.medianDiameterM, 0) + ' m',
          unit: 'median diameter, across the ' + fmt(sc.reported) + ' records that state one',
          delta: null
        },
        chart: barsV(sc.buckets, {
          ariaLabel: 'Formations by diameter band',
          unit: 'formations',
          fill: 'var(--seq-3)'
        }),
        reading: 'A crop formation is a large object: the median is ' +
          fmt(sc.medianDiameterM, 0) + ' metres across and the largest on record ' +
          'runs to ' + fmt(sc.maxDiameterM, 0) + ' m — roughly five football pitches ' +
          'end to end. The distribution is right-skewed, which is why the mean (' +
          fmt(sc.meanDiameterM, 1) + ' m) sits well above the median. The caveat is ' +
          'large: only ' + pct(sc.reportedPct) + ' of records state a diameter at ' +
          'all, and reports that bother to measure are biased toward the ' +
          'impressive ones, so the true archive-wide median is probably lower ' +
          'than this figure.',
        table: tableView(['Diameter band', 'Formations'],
          sc.buckets.map(function (d) { return [d.label, d.value]; }))
      }));

      out[out.length - 1].insertBefore(
        tiles([
          { label: 'Median', value: fmt(sc.medianDiameterM, 0) + ' m', sub: 'across the reported subset' },
          { label: 'Mean', value: fmt(sc.meanDiameterM, 1) + ' m', sub: 'pulled up by the tail' },
          { label: 'Largest', value: fmt(sc.maxDiameterM, 0) + ' m', sub: 'on record' },
          { label: 'Reported', value: pct(sc.reportedPct), sub: 'of records state a size' }
        ]),
        out[out.length - 1].querySelector('.r-reading')
      );
    }

    if (sc && sc.byComplexity && sc.byComplexity.length > 2) {
      out.push(card({
        kicker: 'Size vs complexity',
        title: 'Do the elaborate ones get bigger?',
        chart: barsH(sc.byComplexity.map(function (d) {
          return { label: 'complexity ' + d.label, value: d.value };
        }), {
          ariaLabel: 'Mean diameter by complexity band',
          labelWidth: 160,
          unit: 'm mean diameter',
          valueFormat: function (v) { return fmt(v, 0) + ' m'; }
        }),
        reading: 'Mean diameter within each complexity band. Size and complexity do ' +
          'rise together across the low end, which is close to a tautology — you ' +
          'cannot fit a fifty-element fractal into a twelve-metre circle. The ' +
          'more interesting part is the top: the most elaborate formations are ' +
          'not the largest ones. Whatever the elaborate designs cost to produce, ' +
          'it is evidently not paid for in ground area. Band counts are small at ' +
          'both extremes — hover each bar for the sample behind it.',
        table: tableView(['Complexity band', 'Mean diameter (m)', 'Records with a size'],
          sc.byComplexity.map(function (d) { return [d.label, fmt(d.value, 1), d.n]; }))
      }));
    }

    if (sc && sc.largest && sc.largest.length) {
      out.push(card({
        kicker: 'Extremes',
        title: 'The largest formations on record',
        block: rankList(sc.largest.map(function (d) {
          return {
            label: d.name,
            value: d.diameterM,
            sub: d.where + (d.year ? ' · ' + d.year : '') + ' · complexity ' + d.complexity + '/10'
          };
        }), { colorByIndex: true, format: function (v) { return fmt(v, 0) + ' m'; } }),
        reading: 'The eight biggest by stated diameter. These are the formations ' +
          'that carry the argument in both directions — big enough that the ' +
          'overnight-construction claim gets genuinely demanding, and famous ' +
          'enough that they are also the ones most likely to have had their ' +
          'dimensions inflated in the retelling. Every figure here is as-reported; ' +
          'none has been independently re-surveyed for this archive.',
        table: tableView(['Formation', 'Where', 'Year', 'Diameter (m)', 'Complexity'],
          sc.largest.map(function (d) {
            return [d.name, d.where, d.year || '—', fmt(d.diameterM, 0), d.complexity];
          }))
      }));
    }

    return out;
  }

  // ------------------------------------------------------------- evidence
  // The tab that answers "so what does this actually establish". It joins the
  // research routine's per-formation authenticity verdict (from
  // index/formations.md — a human judgment that exists nowhere in the CSV)
  // with the dataset's own media-coverage field.

  function buildEvidence() {
    var ev = R.evidence, out = [];
    if (!ev) return out;

    var a = ev.authenticity;
    var COLORS = ['var(--cat-2)', 'var(--cat-1)', 'var(--cat-3)', 'var(--div-mid)'];

    out.push(card({
      kicker: 'Verdicts',
      title: 'What the record has actually been ruled on',
      hero: {
        value: fmt(a.assessed),
        unit: 'of ' + fmt(a.total) + ' formations carry an evidence verdict',
        delta: null
      },
      chart: stackedBar(a.counts.map(function (d, i) {
        return { label: d.label, value: d.value, color: COLORS[i] };
      }), { ariaLabel: 'Share of formations by authenticity verdict' }),
      legend: legend(a.counts.map(function (d, i) {
        return { label: d.label + ' — ' + fmt(d.value), color: COLORS[i] };
      })),
      reading: 'Each formation in the research index carries one of four verdicts, ' +
        'assigned by the daily research agent from the sourcing it found. The ' +
        'honest headline is the grey block: ' + fmt(a.counts[3].value) + ' records ' +
        'are still unassessed, so every ratio drawn from this chart is a ratio ' +
        'over the ' + fmt(a.assessed) + ' that have been looked at. Within that ' +
        'assessed set, ' + fmt(a.humanMade) + ' are confirmed human-made — a ' +
        'hoaxer confession, a documented competition, or an admitted marketing ' +
        'stunt — against ' + fmt(a.unexplained) + ' with physical anomaly evidence ' +
        'and no claimant, and ' + fmt(a.contested) + ' where credible people ' +
        'disagree. Note which way the selection bias runs: a formation gets ' +
        'assessed because something about it drew attention, so the assessed set ' +
        'over-represents both confessions and anomalies relative to the quiet ' +
        'majority.',
      table: tableView(['Verdict', 'Formations', 'Share of archive'],
        a.counts.map(function (d) {
          return [d.label, d.value, fmt(100 * d.value / (a.total || 1), 1) + '%'];
        }))
    }));

    if (ev.mediaCoverage && ev.mediaCoverage.length) {
      var known = ev.mediaCoverage.filter(function (d) { return d.label !== 'unknown'; });
      out.push(card({
        kicker: 'Attention',
        title: 'Fame and complexity do not line up',
        chart: barsH(known.map(function (d) {
          return { label: d.label + ' coverage', value: d.meanComplexity };
        }), {
          ariaLabel: 'Mean complexity by level of media coverage',
          labelWidth: 190,
          colorByIndex: true,
          unit: 'mean complexity',
          valueFormat: function (v) { return fmt(v, 2); }
        }),
        reading: 'Mean complexity within each media-coverage tier, across the ' +
          fmt(ev.knownCoverage) + ' records whose coverage is known. If publicity ' +
          'tracked how remarkable a formation is, this would be a staircase. It ' +
          'is not: the "medium coverage" tier carries the highest mean complexity ' +
          'in the archive, well above the very-high-coverage tier. The likeliest ' +
          'reading is that heavy coverage attaches to formations that are ' +
          'accessible, photogenic and near a famous monument, which is not the ' +
          'same property as being structurally elaborate — and that the archive\'s ' +
          'coverage field is itself a coarse after-the-fact judgment. Either way, ' +
          'the formations the public knows are not the formations the data finds ' +
          'most interesting.',
        table: tableView(['Coverage', 'Formations', 'Mean complexity', 'Sacred geometry'],
          ev.mediaCoverage.map(function (d) {
            return [d.label, d.value, fmt(d.meanComplexity, 2), pct(d.sgPct)];
          }))
      }));

      out[out.length - 1].insertBefore(
        tiles(known.map(function (d) {
          return { label: d.label + ' coverage', value: fmt(d.value), sub: 'mean complexity ' + fmt(d.meanComplexity, 2) };
        })),
        out[out.length - 1].querySelector('.r-reading')
      );
    }

    if (ev.flagPct && ev.flagPct.length) {
      out.push(card({
        kicker: 'Anomaly flags',
        title: 'How common each claimed feature actually is',
        chart: barsH(ev.flagPct, {
          ariaLabel: 'Share of the archive flagged with each encoded feature',
          labelWidth: 170,
          colorByIndex: true,
          unit: '% of archive',
          valueFormat: function (v) { return fmt(v, 1) + '%'; }
        }),
        reading: 'The same features the Geometry tab counts, expressed as a share ' +
          'of the whole archive rather than as raw totals — which changes how ' +
          'they read. Sacred geometry is flagged on about a fifth of the record; ' +
          'everything else is a thin minority, and the two features most often ' +
          'cited as evidence of encoded intent, binary messages and Fibonacci ' +
          'sequences, together account for under five per cent. These flags come ' +
          'from source records and the engine\'s scoring, not from independent ' +
          're-measurement, so they mark where to look rather than what is true.',
        table: tableView(['Feature', '% of archive'],
          ev.flagPct.map(function (d) { return [d.label, fmt(d.value, 1) + '%']; }))
      }));
    }

    return out;
  }

  // --------------------------------------------------------- research log
  // The daily scheduled routine, treated as a subject. Everything here comes
  // from the routine's own output files — the session notes, the angle
  // rotation, the licensing leads — rather than from the analytics engine.

  function buildProgramme() {
    var p = R.programme, out = [];
    if (!p) return out;

    out.push(card({
      kicker: 'The routine',
      title: 'A research agent has been running this every morning',
      hero: {
        value: fmt(p.sessions),
        unit: 'daily research sessions since ' + p.firstDate,
        delta: null
      },
      chart: barsV(p.perMonth, {
        ariaLabel: 'Research sessions per month',
        unit: 'sessions',
        fill: 'var(--seq-3)'
      }),
      reading: 'Everything on this page ultimately rests on a scheduled agent that ' +
        'wakes up each morning, picks a research angle it has not covered ' +
        'recently, searches, and writes up what it finds as a dated session ' +
        'file. It has run ' + fmt(p.sessions) + ' times between ' + p.firstDate +
        ' and ' + p.lastDate + ', producing ' + fmt(p.topicsTotal) + ' documented ' +
        'topics — an average of ' + fmt(p.topicsPerSession, 1) + ' per session. ' +
        'Gaps in the monthly bars are days the job did not run or did not clear ' +
        'verification, which is a normal outcome rather than a failure.',
      table: tableView(['Month', 'Sessions'],
        p.perMonth.map(function (d) { return [d.label, d.value]; }))
    }));

    out[out.length - 1].insertBefore(
      tiles([
        { label: 'Sessions', value: fmt(p.sessions), sub: 'since ' + p.firstDate },
        { label: 'Topics documented', value: fmt(p.topicsTotal), sub: 'formations and subjects' },
        { label: 'Per session', value: fmt(p.topicsPerSession, 1), sub: 'average yield' },
        { label: 'Last run', value: p.lastDate, sub: 'most recent session file' }
      ]),
      out[out.length - 1].querySelector('.r-reading')
    );

    if (p.angles && p.angles.length) {
      var top = p.angles.reduce(function (a, b) { return b.value > a.value ? b : a; }, p.angles[0]);
      out.push(card({
        kicker: 'Rotation',
        title: 'What it has been looking at',
        block: rankList(p.angles.slice().sort(function (a, b) { return b.value - a.value; }).map(function (d) {
          return {
            label: d.label,
            value: d.value,
            sub: d.last ? 'last covered ' + d.last : 'never covered'
          };
        }), {
          colorByIndex: true,
          format: function (v) { return fmt(v) + (v === 1 ? ' session' : ' sessions'); }
        }),
        reading: 'The agent rotates through ten standing research angles. The ' +
          'rotation is not even, and deliberately so — but it is worth watching, ' +
          'because it has failed before. "' + top.label + '" has taken ' +
          fmt(top.value) + ' of ' + fmt(p.sessions) + ' sessions, because it is the ' +
          'one open-ended angle in the set: there is always one more country. A ' +
          'meta-analysis of the first 33 sessions found it had consumed 58% of ' +
          'them while thematic angles went five weeks untouched, and the schedule ' +
          'now blocks it if it ran in either of the previous two sessions. This ' +
          'chart is how you check that the guard is still holding.',
        table: tableView(['Angle', 'Sessions', 'Last covered'],
          p.angles.map(function (d) { return [d.label, d.value, d.last || '—']; }))
      }));
    }

    if (p.leads && p.leads.total) {
      var L = p.leads;
      var LCOL = ['var(--cat-1)', 'var(--cat-2)', 'var(--div-mid)'];
      out.push(card({
        kicker: 'Sourcing',
        title: 'Image licensing leads, by what you can actually use',
        hero: {
          value: pct(L.freePct),
          unit: 'of ' + fmt(L.total) + ' logged leads are confirmed free or CC',
          delta: null
        },
        chart: stackedBar(L.counts.map(function (d, i) {
          return { label: d.label, value: d.value, color: LCOL[i] };
        }), { ariaLabel: 'Image leads by licensing status' }),
        legend: legend(L.counts.map(function (d, i) {
          return { label: d.label + ' — ' + fmt(d.value), color: LCOL[i] };
        })),
        reading: 'The research routine logs every image source it finds, tagged by ' +
          'licensing. This is the number that decides whether the archive can ' +
          'ever be published: a commercial lead is a lead, not an image. The ' +
          '"unrecorded" block is leads logged before the tagging rule existed — ' +
          'the routine has been required since June to tag every new lead ' +
          'explicitly and to run at least one open-licence query per session, so ' +
          'the free/CC share should climb and the grey block should stop growing. ' +
          'It is worth restating the harder constraint underneath all of this: no ' +
          'print-resolution image exists anywhere in the free library. Every ' +
          'free source serves web-display copies.',
        table: tableView(['Licensing', 'Leads', 'Share'],
          L.counts.map(function (d) {
            return [d.label, d.value, fmt(100 * d.value / L.total, 1) + '%'];
          }))
      }));
    }

    if (p.recent && p.recent.length) {
      var log = h('ol', 'r-log');
      p.recent.forEach(function (s, i) {
        var li = h('li', 'r-log-entry');
        li.style.transitionDelay = (i * 40) + 'ms';
        var head = h('div', 'r-log-head');
        head.appendChild(h('span', 'r-log-date', s.date));
        head.appendChild(h('span', 'r-log-angle', s.angle));
        li.appendChild(head);
        if (s.topics && s.topics.length) {
          var ul = h('ul', 'r-log-topics');
          s.topics.forEach(function (t) { ul.appendChild(h('li', null, t)); });
          li.appendChild(ul);
        }
        log.appendChild(li);
      });

      out.push(card({
        kicker: 'Latest runs',
        title: 'The last eight mornings',
        block: log,
        reading: 'The most recent sessions, newest first, with the topics each one ' +
          'documented. This is the raw feed the rest of this page is built from — ' +
          'every chart here is a count over these write-ups. Full notes for each ' +
          'run, including sources and the reasoning behind each authenticity ' +
          'verdict, live in the session file for that date in the research repo.'
      }));
    }

    return out;
  }

  function buildHypotheses() {
    var hy = R.hypotheses, out = [];
    var leading = hy.current.reduce(function (a, b) {
      return (b.score || 0) > (a.score || 0) ? b : a;
    }, hy.current[0] || {});

    out.push(card({
      kicker: 'Current standing',
      title: 'Confidence by hypothesis',
      chart: confidenceBars(hy.current, hy.scaleMax),
      reading: 'These are the analytics engine\'s confidence ratings for each ' +
        'candidate explanation, scored from the evidence currently in the ' +
        'archive. The leading position — ' + (leading.name || '—') + ' — is not a ' +
        'claim that the question is settled; it reflects that a record containing ' +
        'both documented human-made formations and unexplained cases is better ' +
        'described by a mixed model than by any single cause. Confidence here ' +
        'means "how well the evidence supports this", not "how likely this is to ' +
        'be true".',
      table: tableView(['Hypothesis', 'Confidence', 'Score'],
        hy.current.map(function (d) { return [d.id + ' ' + d.name, d.label || '—', (d.score == null ? '—' : d.score + '/' + hy.scaleMax)]; }))
    }));

    if (hy.history && hy.history.length > 1) {
      var hist = hy.history;
      // One line per hypothesis over the tracked weeks. Six series → legend
      // plus fixed-order categorical hues.
      var Hgt = 300, padL = 46, padR = 16, padT = 18, padB = 34;
      var plotW = W - padL - padR, plotH = Hgt - padT - padB;
      var n = hist.length;
      var svg = el('svg', {
        'class': 'r-chart', viewBox: '0 0 ' + W + ' ' + Hgt,
        role: 'img', 'aria-label': 'Hypothesis confidence over time'
      });
      var grid = el('g', { 'class': 'r-grid' });
      for (var s = 0; s <= hy.scaleMax; s++) {
        var y = padT + plotH - (s / hy.scaleMax) * plotH;
        grid.appendChild(el('line', { x1: padL, y1: y, x2: W - padR, y2: y }));
        svg.appendChild(el('text', {
          x: padL - 9, y: y + 3.5, 'text-anchor': 'end', 'class': 'r-axis-label'
        }, String(s)));
      }
      svg.insertBefore(grid, svg.firstChild);

      hy.current.forEach(function (hyp, hi) {
        var d = hist.map(function (row, i) {
          var x = n === 1 ? padL + plotW / 2 : padL + (i / (n - 1)) * plotW;
          var yy = padT + plotH - ((row.scores[hi] || 0) / hy.scaleMax) * plotH;
          return (i ? 'L' : 'M') + x.toFixed(1) + ' ' + yy.toFixed(1);
        }).join(' ');
        var p = el('path', { d: d, stroke: catVar(hi), 'class': 'r-line' });
        p.setAttribute('stroke-opacity', '0.9');
        svg.appendChild(p);
        var lastX = padL + plotW, lastY = padT + plotH - ((hist[n - 1].scores[hi] || 0) / hy.scaleMax) * plotH;
        var dot = el('circle', { cx: lastX, cy: lastY, r: 4.5, fill: catVar(hi), 'class': 'r-dot' });
        svg.appendChild(dot);
        hoverable(dot, hyp.id + ' ' + hyp.name, 'now ' + (hyp.label || '—'));
      });

      hist.forEach(function (row, i) {
        if (i % Math.max(1, Math.ceil(n / 8)) && i !== n - 1) return;
        svg.appendChild(el('text', {
          x: n === 1 ? padL + plotW / 2 : padL + (i / (n - 1)) * plotW,
          y: Hgt - 12, 'text-anchor': 'middle', 'class': 'r-axis-label'
        }, row.week.replace('2026-', '')));
      });
      var axis = el('g', { 'class': 'r-axis' });
      axis.appendChild(el('line', { x1: padL, y1: padT + plotH, x2: W - padR, y2: padT + plotH }));
      svg.appendChild(axis);

      out.push(card({
        kicker: 'Over time',
        title: 'How confidence has shifted',
        chart: svg,
        legend: legend(hy.current.map(function (hyp, i) {
          return { label: hyp.id + ' ' + hyp.name, color: catVar(i) };
        })),
        reading: 'Each line tracks one hypothesis across the weekly analysis runs. ' +
          'The large step change corresponds to the dataset roughly quadrupling ' +
          'in size — when the archive grew from the seed set to the full research ' +
          'record, several ratings moved at once. Stability since then reflects a ' +
          'settled dataset, not a settled question.',
        table: tableView(['Week'].concat(hy.current.map(function (x) { return x.id; })),
          hist.map(function (r) { return [r.week].concat(r.scores); }))
      }));
    }

    return out;
  }

  function buildHealth() {
    var hl = R.health, out = [];

    if (hl.growth && hl.growth.length) {
      out.push(card({
        kicker: 'Coverage',
        title: 'Archive growth, week by week',
        hero: {
          value: fmt(R.metrics.total),
          unit: 'formations in the dataset',
          delta: deltaChip(R.deltas.total, '', { digits: 0 })
        },
        chart: lineChart(hl.growth.map(function (d) {
          return { label: d.week.replace('2026-', ''), value: d.value };
        }), { ariaLabel: 'Dataset size by analysis week', unit: 'formations', stroke: 'var(--seq-4)' }),
        reading: 'Dataset size at each weekly run. The step is the point where the ' +
          'seed dataset was replaced by the full research archive; growth since ' +
          'then comes from the daily research agent. A flat week means no new ' +
          'formations cleared verification — which is a normal outcome, not a ' +
          'failure of the scan.',
        table: tableView(['Week', 'Formations'],
          hl.growth.map(function (d) { return [d.week, d.value]; }))
      }));
    }

    out.push(card({
      kicker: 'Data quality',
      title: 'Field completeness',
      chart: barsH(hl.completeness, {
        ariaLabel: 'Percentage of records with each field populated',
        labelWidth: 170,
        unit: '% populated',
        valueFormat: function (v) { return fmt(v, 1) + '%'; }
      }),
      reading: 'How much of each field is actually populated across the archive. ' +
        'Coordinates and complexity are near-complete; physical measurements like ' +
        'diameter are the weakest, because most source reports simply never state ' +
        'one. Any statistic derived from a sparse field carries that gap with it — ' +
        'the mean diameter is a mean over the subset that reported a diameter, not ' +
        'over the archive.',
      table: tableView(['Field', '% populated'],
        hl.completeness.map(function (d) { return [d.label, d.value + '%']; }))
    }));

    out.push(card({
      kicker: 'Known gaps',
      title: 'What this dataset cannot tell you',
      reading: 'Three limits worth stating outright. First, ' + fmt(hl.unknownMediaCoverage) +
        ' records have unknown media coverage, so anything about publicity is ' +
        'unreliable. Second, the archive is a record of *reports*, and reporting ' +
        'effort is concentrated in one county of one country — geographic patterns ' +
        'partly measure where people are looking. Third, the confidence ratings ' +
        'are an evidence-weighting exercise by an automated pipeline, not peer ' +
        'review. The value here is in the shape of the record and in knowing ' +
        'exactly where it is thin.'
    }));

    return out;
  }

  // ----------------------------------------------------------------- render

  var elFeed = document.getElementById('researchFeed');
  var elTabs = document.getElementById('researchTabs');

  var observer = ('IntersectionObserver' in window)
    ? new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          if (e.isIntersecting) {
            e.target.classList.add('is-in');
            observer.unobserve(e.target);
          }
        });
      }, { rootMargin: '0px 0px -8% 0px', threshold: 0.06 })
    : null;

  function selectTab(id) {
    [].forEach.call(elTabs.children, function (b) {
      b.setAttribute('aria-selected', String(b.dataset.tab === id));
    });
    elFeed.innerHTML = '';
    hideTip();
    var tab = TABS.filter(function (t) { return t.id === id; })[0];
    if (!tab) return;
    tab.build().forEach(function (c) {
      elFeed.appendChild(c);
      if (observer) observer.observe(c);
      else c.classList.add('is-in');
    });
    try {
      history.replaceState(null, '', '#' + id);
    } catch (e) { /* file:// — harmless */ }
  }

  function renderStamp() {
    var span = R.time && R.time.yearRange;
    var set = function (id, v) {
      var n = document.getElementById(id);
      if (n) n.textContent = v;
    };
    set('rsTotal', fmt(R.metrics.total) + ' formations');
    set('rsWeek', R.week || '—');
    set('rsSpan', span ? span[0] + '–' + span[1] : '—');

    // Same scan stamp the other two pages show, in the header chip and footer.
    if (meta.lastScan) {
      var stamp;
      try {
        stamp = new Intl.DateTimeFormat(undefined, {
          month: 'short', day: 'numeric', hour: 'numeric',
          minute: '2-digit', timeZoneName: 'short'
        }).format(new Date(meta.lastScan)).toUpperCase();
      } catch (e) { stamp = meta.lastScan; }
      ['statScan', 'footerUpdated'].forEach(function (id) {
        var n = document.getElementById(id);
        if (n) n.textContent = stamp;
      });
    }
  }

  function init() {
    if (!R) {
      elFeed.innerHTML =
        '<p class="r-reading">Research data hasn\'t been generated yet. Run ' +
        '<code>python3 analytics/export_research_json.py</code> to build ' +
        '<code>research.js</code>.</p>';
      return;
    }

    TABS.forEach(function (t, i) {
      var b = h('button', 'research-tab', t.label);
      b.type = 'button';
      b.dataset.tab = t.id;
      b.setAttribute('role', 'tab');
      b.setAttribute('aria-selected', String(i === 0));
      b.addEventListener('click', function () { selectTab(t.id); });
      elTabs.appendChild(b);
    });

    renderStamp();

    var fromHash = (location.hash || '').replace('#', '');
    var initial = TABS.some(function (t) { return t.id === fromHash; }) ? fromHash : TABS[0].id;
    selectTab(initial);
  }

  init();
})();
